// Package direnv owns the direnv activation backend: generating and parsing
// .envrc files, controlling direnv (allow/deny/reload), silencing direnv output
// and migrating legacy projects. It is the first activation backend; the
// Activator interface that makes it interchangeable lands in v3.1.
package direnv

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/s1ks1/bwenv/v3/internal/config"
	"github.com/s1ks1/bwenv/v3/internal/project"
	"github.com/s1ks1/bwenv/v3/internal/shell"
)

// generatedDirenvLogFormat and generatedDirenvTimeout are the exact lines
// bwenv writes into .envrc and the shell RC. Migration matches them verbatim,
// so they must not change without a migration update.
const (
	generatedDirenvLogFormat = `export DIRENV_LOG_FORMAT=$'\033[2m  \U0001f510 %s\033[0m'`
	generatedDirenvTimeout   = `export DIRENV_WARN_TIMEOUT="10m"`
)

// Config holds the parameters needed to generate a .envrc file. These are
// collected during the interactive init flow and written into the .envrc so
// that "bwenv export" can reconstruct the same context when direnv loads it.
type Config struct {
	// ProviderSlug is the short identifier for the chosen provider (e.g. "bitwarden").
	ProviderSlug string

	// FolderName is the human-readable folder name chosen by the user.
	FolderName string

	// FolderID is the provider-specific unique identifier for the folder.
	// Stored in .bwenv.toml so we don't look it up by name every time.
	FolderID string

	// Session is the authentication token (e.g. BW_SESSION for Bitwarden).
	// For providers that manage sessions internally (like 1Password), this may be empty.
	Session string

	// Version is the bwenv version that generated this file (for debugging).
	Version string

	// ItemIDs are the specific secret item IDs the user selected during init.
	ItemIDs []string `json:"item_ids,omitempty"`

	// ItemNames are the human-readable item names (for the .envrc header only).
	ItemNames []string `json:"item_names,omitempty"`
}

// Generate creates a .envrc file in the current directory. The generated file
// uses direnv's eval mechanism to call "bwenv export", which fetches secrets
// from the configured provider and folder at shell load time.
//
// Key design decisions in the generated .envrc:
//
//   - DIRENV_LOG_FORMAT is set to a styled value to suppress direnv's own
//     export/unload messages. This takes effect on the SECOND load and onward;
//     for first-load suppression see SilenceGlobally().
//   - DIRENV_WARN_TIMEOUT uses Go duration format ("10m") required by direnv v2.30+.
//   - BW_SESSION is stored in .envrc for Bitwarden users; it is never written
//     to the separate .bwenv.toml project metadata file.
func Generate(cfg Config) error {
	// Load user preferences to decide whether to silence direnv output.
	userCfg, _ := config.Load()

	var b strings.Builder

	// -- Header with metadata --
	b.WriteString("# ═══════════════════════════════════════════════════════════════\n")
	b.WriteString(fmt.Sprintf("# Generated by bwenv %s on %s\n",
		cfg.Version, time.Now().Format("2006-01-02 15:04:05")))
	if len(cfg.ItemNames) > 0 {
		b.WriteString(fmt.Sprintf("# Provider: %s | Folder: %s | Items: %s\n",
			cfg.ProviderSlug, cfg.FolderName, strings.Join(cfg.ItemNames, ", ")))
	} else {
		b.WriteString(fmt.Sprintf("# Provider: %s | Folder: %s\n", cfg.ProviderSlug, cfg.FolderName))
	}
	b.WriteString("#\n")
	b.WriteString("# DO NOT edit manually — re-run 'bwenv init' to regenerate.\n")
	b.WriteString("# ═══════════════════════════════════════════════════════════════\n")
	b.WriteString("\n")

	// -- Silence direnv's log output (unless user opted to see it) --
	if !userCfg.ShowDirenvOutput {
		b.WriteString("# Replace direnv's noisy output with a subtle, styled message\n")
		b.WriteString("export DIRENV_LOG_FORMAT=$'\\033[2m  \\U0001f510 %s\\033[0m'\n")
		b.WriteString("\n")
	} else {
		b.WriteString("# Direnv output is visible (configured via 'bwenv config')\n")
		b.WriteString("\n")
	}

	// -- Set a generous timeout --
	// Vault operations can take several seconds; direnv warns after 5s by
	// default and that looks like an error. Go duration format is required.
	b.WriteString("# Generous timeout for vault operations (Go duration format for direnv v2.30+)\n")
	b.WriteString("export DIRENV_WARN_TIMEOUT=\"10m\"\n")
	b.WriteString("\n")

	// -- Bitwarden session token (if applicable) --
	if cfg.Session != "" {
		b.WriteString("# Bitwarden session token (required for vault access)\n")
		b.WriteString("# This token expires — run 'bwenv login' to re-authenticate.\n")
		b.WriteString(fmt.Sprintf("export BW_SESSION=%s\n", shell.Quote(cfg.Session)))
		b.WriteString("\n")
	}

	// -- The main payload --
	b.WriteString("# Load secrets from the provider into the environment\n")
	exportCommand := ""
	if cfg.FolderID != "" {
		projectCfg := project.Config{
			Version:  project.ConfigVersion,
			Provider: cfg.ProviderSlug,
			Project: project.Metadata{
				FolderID:   cfg.FolderID,
				FolderName: cfg.FolderName,
				Items:      cfg.ItemIDs,
			},
			Activation: project.Activation{Mode: "direnv"},
		}
		if err := project.Write(".bwenv.toml", projectCfg); err != nil {
			return err
		}
		exportCommand = "bwenv export --project ."
	} else {
		if err := os.Remove(".bwenv.toml"); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("remove stale .bwenv.toml: %w", err)
		}
		exportCommand = fmt.Sprintf("bwenv export --provider %s",
			shell.Escape(cfg.ProviderSlug))
		exportCommand += " --folder " + shell.Quote(cfg.FolderName)
		if len(cfg.ItemIDs) > 0 {
			exportCommand += " --items " + shell.Quote(strings.Join(cfg.ItemIDs, ","))
		}
	}
	b.WriteString(fmt.Sprintf("eval \"$(%s)\"\n", exportCommand))

	// Write the file with restrictive permissions (owner read/write only).
	if err := os.WriteFile(".envrc", []byte(b.String()), 0600); err != nil {
		return fmt.Errorf("failed to write .envrc: %w", err)
	}

	return nil
}

// UpdateSession replaces the BW_SESSION token in the existing .envrc file with a
// fresh one. It is called after re-authenticating so subsequent direnv loads use
// the new token. It is a no-op when .envrc has no BW_SESSION line (e.g. 1Password).
func UpdateSession(newSession string) error {
	if newSession == "" {
		return nil // Nothing to update (e.g. 1Password doesn't use session tokens).
	}

	content, err := os.ReadFile(".envrc")
	if err != nil {
		return fmt.Errorf("could not read .envrc: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	found := false
	newLine := fmt.Sprintf("export BW_SESSION=%s", shell.Quote(newSession))

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "export BW_SESSION=") {
			lines[i] = newLine
			found = true
			break
		}
	}

	if !found {
		return nil
	}

	if err := os.WriteFile(".envrc", []byte(strings.Join(lines, "\n")), 0600); err != nil {
		return fmt.Errorf("failed to update .envrc: %w", err)
	}

	return nil
}

// Allow runs "direnv allow" in the current directory so the user doesn't have
// to do it manually after "bwenv init". Non-fatal when direnv is not installed.
func Allow() error {
	if _, err := exec.LookPath("direnv"); err != nil {
		return fmt.Errorf("direnv not found in PATH")
	}

	cmd := exec.Command("direnv", "allow")
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard // Suppress "direnv:" messages
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("'direnv allow' failed: %w", err)
	}

	return nil
}

// Disallow runs "direnv deny" in the current directory to block the .envrc.
func Disallow() error {
	if _, err := exec.LookPath("direnv"); err != nil {
		return fmt.Errorf("direnv not found in PATH")
	}

	cmd := exec.Command("direnv", "deny")
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard // Suppress "direnv:" messages
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("'direnv deny' failed: %w", err)
	}

	return nil
}

// Reload asks direnv to reload the current project's environment.
func Reload() error {
	if _, err := exec.LookPath("direnv"); err != nil {
		return fmt.Errorf("direnv is not installed; install it before refreshing the environment")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "direnv", "reload")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("direnv could not reload the project environment; check the shell hook and .envrc approval: %w", err)
	}
	return nil
}

// ParseConfig reads the project in the current directory and extracts the
// provider slug, folder name, and optional item IDs.
func ParseConfig() (providerSlug string, folderName string, itemIDs []string, err error) {
	providerSlug, folderName, _, itemIDs, err = ParseConfigWithFolderID()
	return providerSlug, folderName, itemIDs, err
}

// ParseConfigWithFolderID also returns the persisted provider folder ID.
// Older .envrc files return an empty ID and use the legacy name path.
func ParseConfigWithFolderID() (providerSlug string, folderName string, folderID string, itemIDs []string, err error) {
	projectConfig, projectErr := project.Load(".bwenv.toml")
	if projectErr == nil {
		return projectConfig.Provider, projectConfig.Project.FolderName, projectConfig.Project.FolderID, projectConfig.Project.Items, nil
	}
	if !errors.Is(projectErr, os.ErrNotExist) {
		return "", "", "", nil, projectErr
	}

	content, err := os.ReadFile(".envrc")
	if err != nil {
		return "", "", "", nil, fmt.Errorf("no .envrc found in current directory")
	}

	contentStr := string(content)

	if !strings.Contains(contentStr, "bwenv") {
		return "", "", "", nil, fmt.Errorf(".envrc was not generated by bwenv")
	}

	// Try to extract from the header comment first:
	// Format: "# Provider: bitwarden | Folder: MySecrets"
	for _, line := range strings.Split(contentStr, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "# Provider:") {
			parts := strings.SplitN(line, "|", 3)
			if len(parts) >= 1 {
				provPart := strings.TrimPrefix(parts[0], "# Provider:")
				providerSlug = strings.TrimSpace(provPart)
			}
			if len(parts) >= 2 {
				folderPart := strings.TrimPrefix(parts[1], " Folder:")
				folderName = strings.TrimSpace(folderPart)
			}
			break
		}
	}

	// The export command is authoritative for IDs; the header holds display names.
	for _, line := range strings.Split(contentStr, "\n") {
		line = strings.TrimSpace(line)
		if !strings.Contains(line, "bwenv export") {
			continue
		}
		if providerSlug == "" {
			providerSlug = extractShellFlag(line, "--provider")
		}
		if folderName == "" {
			folderName = extractShellFlag(line, "--folder")
		}
		folderID = extractShellFlag(line, "--folder-id")
		if itemsValue := extractShellFlag(line, "--items"); itemsValue != "" {
			for _, id := range strings.Split(itemsValue, ",") {
				if id = strings.TrimSpace(id); id != "" {
					itemIDs = append(itemIDs, id)
				}
			}
		}
		break
	}

	if providerSlug == "" || folderName == "" {
		return providerSlug, folderName, folderID, nil, fmt.Errorf("could not extract provider and folder from .envrc")
	}

	return providerSlug, folderName, folderID, itemIDs, nil
}

func extractShellFlag(line string, flag string) string {
	for offset := 0; offset < len(line); {
		idx := strings.Index(line[offset:], flag)
		if idx < 0 {
			return ""
		}
		start := offset + idx
		end := start + len(flag)
		offset = end
		if start > 0 && line[start-1] != ' ' && line[start-1] != '\t' {
			continue
		}
		if end < len(line) && line[end] != '=' && line[end] != ' ' && line[end] != '\t' {
			continue
		}

		rest := strings.TrimSpace(line[end:])
		if strings.HasPrefix(rest, "=") {
			rest = strings.TrimSpace(strings.TrimPrefix(rest, "="))
		}
		if len(rest) > 0 && (rest[0] == '\'' || rest[0] == '"') {
			quote := rest[0]
			if end := strings.IndexByte(rest[1:], quote); end >= 0 {
				return rest[1 : end+1]
			}
			return ""
		}
		if fields := strings.Fields(rest); len(fields) > 0 {
			return strings.Trim(fields[0], "'\")")
		}
		return ""
	}
	return ""
}

// SilenceGlobally adds the styled DIRENV_LOG_FORMAT and DIRENV_WARN_TIMEOUT to
// the user's shell RC file so ALL direnv messages (including the "loading"
// message printed before .envrc runs) are suppressed from the very first cd.
// It is idempotent: if the lines already exist it changes nothing.
func SilenceGlobally() (modified bool, filePath string, err error) {
	const silenceLine = `export DIRENV_LOG_FORMAT=$'\033[2m  \U0001f510 %s\033[0m'`
	const timeoutLine = `export DIRENV_WARN_TIMEOUT="10m"`
	const markerLog = "DIRENV_LOG_FORMAT"
	const markerTimeout = "DIRENV_WARN_TIMEOUT"

	rcPath, err := shell.DetectRC()
	if err != nil {
		return false, "", err
	}

	displayPath := shell.ShortenHomePath(rcPath)

	content, err := os.ReadFile(rcPath)
	if err != nil && !os.IsNotExist(err) {
		return false, displayPath, fmt.Errorf("could not read %s: %w", displayPath, err)
	}

	contentStr := string(content)
	hasLog := strings.Contains(contentStr, markerLog)
	hasTimeout := strings.Contains(contentStr, markerTimeout)

	if hasLog && hasTimeout {
		return false, displayPath, nil
	}

	var appendContent string
	if !hasLog || !hasTimeout {
		appendContent += "\n# Silence direnv messages — bwenv provides its own styled output\n"
	}
	if !hasLog {
		appendContent += silenceLine + "\n"
	}
	if !hasTimeout {
		appendContent += timeoutLine + "\n"
	}

	f, err := os.OpenFile(rcPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return false, displayPath, fmt.Errorf("could not write to %s: %w", displayPath, err)
	}
	defer f.Close()

	if _, err := f.WriteString(appendContent); err != nil {
		return false, displayPath, fmt.Errorf("failed to append to %s: %w", displayPath, err)
	}

	return true, displayPath, nil
}
