// Package direnv owns the direnv activation backend: generating and parsing
// .envrc files, controlling direnv (allow/deny/reload), silencing direnv output
// and migrating legacy projects.
package direnv

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/s1ks1/bwenv/v3/internal/activation"
	"github.com/s1ks1/bwenv/v3/internal/project"
	"github.com/s1ks1/bwenv/v3/internal/shell"
)

// generatedDirenvLogFormat and generatedDirenvTimeout identify legacy generated
// settings so migration can safely remove them from old .envrc files.
const (
	generatedDirenvLogFormat = `export DIRENV_LOG_FORMAT=$'\033[2m  \U0001f510 %s\033[0m'`
	generatedDirenvTimeout   = `export DIRENV_WARN_TIMEOUT="10m"`
)

// Generate creates a .envrc file in the current directory. The generated file
// uses direnv's eval mechanism to call "bwenv export", which fetches secrets
// from the configured provider and folder at shell load time.
//
// Render builds a .envrc that only delegates activation to bwenv. Project
// references live in .bwenv.toml and session tokens remain in the shell.
func Render(activation.Config) ([]byte, error) {
	return []byte("# Generated by bwenv. Project settings are in .bwenv.toml.\neval \"$(bwenv export --project .)\"\n"), nil
}

// Install writes the project metadata and the generated .envrc with restrictive
// permissions (owner read/write only).
func Install(cfg activation.Config) error {
	content, err := Render(cfg)
	if err != nil {
		return err
	}

	if err := activation.WriteProject(cfg, "direnv"); err != nil {
		return err
	}

	if err := os.WriteFile(".envrc", content, 0600); err != nil {
		return fmt.Errorf("failed to write .envrc: %w", err)
	}

	return nil
}

// Remove deletes the .envrc activation artifact and revokes direnv's approval.
// It leaves .bwenv.toml to the caller.
func Remove() error {
	_ = Disallow()
	if err := os.Remove(".envrc"); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove .envrc: %w", err)
	}
	return nil
}

// Allow runs "direnv allow" in the current directory so the user doesn't have
// to do it manually after "bwenv init". Non-fatal when direnv is not installed.
func Allow() error {
	if err := EnsureLoggingConfig(); err != nil {
		return fmt.Errorf("configure direnv output: %w", err)
	}
	if _, err := exec.LookPath("direnv"); err != nil {
		return fmt.Errorf("direnv not found in PATH")
	}

	cmd := exec.Command("direnv", "allow")
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard // Suppress "direnv:" messages
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("'direnv allow' failed: %w", err)
	}

	return nil
}

// Disallow runs "direnv deny" in the current directory to block the .envrc.
func Disallow() error {
	if _, err := exec.LookPath("direnv"); err != nil {
		return fmt.Errorf("direnv not found in PATH")
	}

	cmd := exec.Command("direnv", "deny")
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard // Suppress "direnv:" messages
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("'direnv deny' failed: %w", err)
	}

	return nil
}

// Reload asks direnv to reload the current project's environment.
func Reload() error {
	if _, err := exec.LookPath("direnv"); err != nil {
		return fmt.Errorf("direnv is not installed; install it before refreshing the environment")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "direnv", "reload")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("direnv could not reload the project environment; check the shell hook and .envrc approval: %w", err)
	}
	return nil
}

// ParseConfig reads the project in the current directory and extracts the
// provider slug, folder name, and optional item IDs.
func ParseConfig() (providerSlug string, folderName string, itemIDs []string, err error) {
	providerSlug, folderName, _, itemIDs, err = ParseConfigWithFolderID()
	return providerSlug, folderName, itemIDs, err
}

// ParseConfigWithFolderID also returns the persisted provider folder ID.
// Older .envrc files return an empty ID and use the legacy name path.
func ParseConfigWithFolderID() (providerSlug string, folderName string, folderID string, itemIDs []string, err error) {
	projectConfig, projectErr := project.Load(".bwenv.toml")
	if projectErr == nil {
		return projectConfig.Provider, projectConfig.Project.FolderName, projectConfig.Project.FolderID, projectConfig.Project.Items, nil
	}
	if !errors.Is(projectErr, os.ErrNotExist) {
		return "", "", "", nil, projectErr
	}

	content, err := os.ReadFile(".envrc")
	if err != nil {
		return "", "", "", nil, fmt.Errorf("no .envrc found in current directory")
	}

	contentStr := string(content)

	if !strings.Contains(contentStr, "bwenv") {
		return "", "", "", nil, fmt.Errorf(".envrc was not generated by bwenv")
	}

	// Try to extract from the header comment first:
	// Format: "# Provider: bitwarden | Folder: MySecrets"
	for _, line := range strings.Split(contentStr, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "# Provider:") {
			parts := strings.SplitN(line, "|", 3)
			if len(parts) >= 1 {
				provPart := strings.TrimPrefix(parts[0], "# Provider:")
				providerSlug = strings.TrimSpace(provPart)
			}
			if len(parts) >= 2 {
				folderPart := strings.TrimPrefix(parts[1], " Folder:")
				folderName = strings.TrimSpace(folderPart)
			}
			break
		}
	}

	// The export command is authoritative for IDs; the header holds display names.
	for _, line := range strings.Split(contentStr, "\n") {
		line = strings.TrimSpace(line)
		if !strings.Contains(line, "bwenv export") {
			continue
		}
		if providerSlug == "" {
			providerSlug = extractShellFlag(line, "--provider")
		}
		if folderName == "" {
			folderName = extractShellFlag(line, "--folder")
		}
		folderID = extractShellFlag(line, "--folder-id")
		if itemsValue := extractShellFlag(line, "--items"); itemsValue != "" {
			for _, id := range strings.Split(itemsValue, ",") {
				if id = strings.TrimSpace(id); id != "" {
					itemIDs = append(itemIDs, id)
				}
			}
		}
		break
	}

	if providerSlug == "" || folderName == "" {
		return providerSlug, folderName, folderID, nil, fmt.Errorf("could not extract provider and folder from .envrc")
	}

	return providerSlug, folderName, folderID, itemIDs, nil
}

func extractShellFlag(line string, flag string) string {
	for offset := 0; offset < len(line); {
		idx := strings.Index(line[offset:], flag)
		if idx < 0 {
			return ""
		}
		start := offset + idx
		end := start + len(flag)
		offset = end
		if start > 0 && line[start-1] != ' ' && line[start-1] != '\t' {
			continue
		}
		if end < len(line) && line[end] != '=' && line[end] != ' ' && line[end] != '\t' {
			continue
		}

		rest := strings.TrimSpace(line[end:])
		if strings.HasPrefix(rest, "=") {
			rest = strings.TrimSpace(strings.TrimPrefix(rest, "="))
		}
		if len(rest) > 0 && rest[0] == '\'' {
			// Single-quoted values may contain escaped quotes (the '\'' that
			// shell.Quote emits for apostrophes); scan to the real closing
			// quote, then unescape with the canonical helper (PER-44).
			tokenEnd := singleQuoteTokenEnd(rest)
			if tokenEnd < 0 {
				return ""
			}
			if value, ok := unquoteShellValue(rest[:tokenEnd]); ok {
				return value
			}
			return ""
		}
		if len(rest) > 0 && rest[0] == '"' {
			if end := strings.IndexByte(rest[1:], '"'); end >= 0 {
				return rest[1 : end+1]
			}
			return ""
		}
		if fields := strings.Fields(rest); len(fields) > 0 {
			return strings.Trim(fields[0], "'\")")
		}
		return ""
	}
	return ""
}

// singleQuoteTokenEnd returns the byte offset just past the closing single
// quote of a shell-quoted token, skipping over '\” escape sequences.
// Returns -1 when the token is never closed.
func singleQuoteTokenEnd(s string) int {
	if len(s) == 0 || s[0] != '\'' {
		return -1
	}
	for i := 1; i < len(s); {
		if strings.HasPrefix(s[i:], `'\''`) {
			i += 4
			continue
		}
		if s[i] == '\'' {
			return i + 1
		}
		i++
	}
	return -1
}

// SilenceGlobally adds the styled DIRENV_LOG_FORMAT and DIRENV_WARN_TIMEOUT to
// the user's shell RC file so ALL direnv messages (including the "loading"
// message printed before .envrc runs) are suppressed from the very first cd.
// It is idempotent: if the lines already exist it changes nothing.
func SilenceGlobally() (modified bool, filePath string, err error) {
	if err := EnsureLoggingConfig(); err != nil {
		return false, "", err
	}
	const silenceLine = `export DIRENV_LOG_FORMAT=""`
	const timeoutLine = `export DIRENV_WARN_TIMEOUT="10m"`
	const markerLog = "DIRENV_LOG_FORMAT"
	const markerTimeout = "DIRENV_WARN_TIMEOUT"

	rcPath, err := shell.DetectRC()
	if err != nil {
		return false, "", err
	}

	displayPath := shell.ShortenHomePath(rcPath)

	content, err := os.ReadFile(rcPath)
	if err != nil && !os.IsNotExist(err) {
		return false, displayPath, fmt.Errorf("could not read %s: %w", displayPath, err)
	}

	contentStr := string(content)
	hasLog := strings.Contains(contentStr, markerLog)
	hasTimeout := strings.Contains(contentStr, markerTimeout)

	if hasLog && hasTimeout {
		return false, displayPath, nil
	}

	var appendContent string
	if !hasLog || !hasTimeout {
		appendContent += "\n# Silence direnv messages — bwenv provides its own styled output\n"
	}
	if !hasLog {
		appendContent += silenceLine + "\n"
	}
	if !hasTimeout {
		appendContent += timeoutLine + "\n"
	}

	f, err := os.OpenFile(rcPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return false, displayPath, fmt.Errorf("could not write to %s: %w", displayPath, err)
	}
	defer f.Close()

	if _, err := f.WriteString(appendContent); err != nil {
		return false, displayPath, fmt.Errorf("failed to append to %s: %w", displayPath, err)
	}

	return true, displayPath, nil
}

// EnsureLoggingConfig works around direnv 2.37.1 ignoring DIRENV_LOG_FORMAT
// unless a TOML config exists. Never replace existing user configuration.
func EnsureLoggingConfig() error {
	dir := os.Getenv("DIRENV_CONFIG")
	if dir == "" {
		base := os.Getenv("XDG_CONFIG_HOME")
		if base == "" {
			home, err := os.UserHomeDir()
			if err != nil {
				return err
			}
			base = filepath.Join(home, ".config")
		}
		dir = filepath.Join(base, "direnv")
	}
	for _, name := range []string{"direnv.toml", "config.toml"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
			return nil
		} else if !os.IsNotExist(err) {
			return err
		}
	}
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}
	file, err := os.OpenFile(filepath.Join(dir, "direnv.toml"), os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if os.IsExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	_, err = file.WriteString("# Enable DIRENV_LOG_FORMAT support in direnv 2.37.1.\n[global]\n")
	closeErr := file.Close()
	if err != nil {
		return err
	}
	return closeErr
}
