// Package envrc handles generating .envrc files and exporting environment
// variables from secret providers. It provides two main capabilities:
//
//  1. Generate() — creates a .envrc file that calls "bwenv export" via direnv.
//  2. Export() — fetches secrets from a provider and prints "export KEY=VALUE"
//     lines to stdout, designed to be eval'd by direnv or the shell.
package envrc

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/s1ks1/bwenv/internal/provider"
)

// Config holds all the parameters needed to generate a .envrc file.
// These are collected during the interactive init flow and written into
// the .envrc so that "bwenv export" can reconstruct the same context
// when direnv loads the file later.
type Config struct {
	// ProviderSlug is the short identifier for the chosen provider (e.g. "bitwarden").
	ProviderSlug string

	// FolderName is the human-readable folder name chosen by the user.
	FolderName string

	// FolderID is the provider-specific unique identifier for the folder.
	// Stored in the .envrc so we don't have to look it up by name every time.
	FolderID string

	// Session is the authentication token (e.g. BW_SESSION for Bitwarden).
	// For providers that manage sessions internally (like 1Password v2), this may be empty.
	Session string

	// Version is the bwenv version that generated this file (for debugging).
	Version string
}

// Generate creates a .envrc file in the current directory. The generated file
// uses direnv's eval mechanism to call "bwenv export", which fetches secrets
// from the configured provider and folder at shell load time.
//
// The .envrc file is self-contained — it stores the provider slug and folder
// name so that "bwenv export" knows what to fetch without any external config.
func Generate(cfg Config) error {
	// Build the .envrc content line by line.
	var b strings.Builder

	// Header with metadata so users know this file is auto-generated.
	b.WriteString("# =============================================================\n")
	b.WriteString(fmt.Sprintf("# Generated by bwenv %s on %s\n", cfg.Version, time.Now().Format("2006-01-02 15:04:05")))
	b.WriteString("# Provider: " + cfg.ProviderSlug + " | Folder: " + cfg.FolderName + "\n")
	b.WriteString("#\n")
	b.WriteString("# DO NOT edit manually — re-run 'bwenv init' to regenerate.\n")
	b.WriteString("# =============================================================\n")
	b.WriteString("\n")

	// Suppress direnv's slow-execution warning since vault operations can be slow.
	b.WriteString("# Suppress direnv slow-execution warning (vault operations may take a few seconds)\n")
	b.WriteString("export DIRENV_WARN_TIMEOUT=600\n")
	b.WriteString("\n")

	// For Bitwarden, we need to persist the BW_SESSION token in the .envrc
	// so that subsequent "bwenv export" calls can access the vault.
	// NOTE: The session token is sensitive — the .envrc should be gitignored.
	if cfg.Session != "" {
		b.WriteString("# Bitwarden session token (required for vault access)\n")
		b.WriteString("# This token expires — re-run 'bwenv init' if you get auth errors.\n")
		b.WriteString(fmt.Sprintf("export BW_SESSION=%q\n", cfg.Session))
		b.WriteString("\n")
	}

	// The main payload: eval the output of "bwenv export" to load secrets.
	// We use eval so that the export statements printed by bwenv become
	// actual environment variable assignments in the current shell.
	b.WriteString("# Load secrets from the provider into the environment\n")
	b.WriteString(fmt.Sprintf("eval \"$(bwenv export --provider %s --folder %q)\"\n",
		shellEscape(cfg.ProviderSlug),
		cfg.FolderName,
	))

	// Write the file with restrictive permissions (owner read/write only).
	// The .envrc contains sensitive information (session tokens, secret references).
	err := os.WriteFile(".envrc", []byte(b.String()), 0600)
	if err != nil {
		return fmt.Errorf("failed to write .envrc: %w", err)
	}

	return nil
}

// Export fetches secrets from the specified provider and folder, then prints
// "export KEY=VALUE" lines to stdout. This function is designed to be called
// from within an .envrc file via eval:
//
//	eval "$(bwenv export --provider bitwarden --folder MyFolder)"
//
// Errors are written to stderr so they don't corrupt the eval output.
// The function returns an error only for fatal issues (provider not found,
// auth failure, etc.).
func Export(providerSlug string, folderName string) error {
	// Look up the requested provider from the registry.
	p, err := provider.Get(providerSlug)
	if err != nil {
		return fmt.Errorf("provider lookup failed: %w", err)
	}

	// Check that the provider's CLI tool is available on this system.
	if !p.IsAvailable() {
		return fmt.Errorf("provider %q requires '%s' CLI which is not installed",
			p.Name(), p.CLICommand())
	}

	// Authenticate with the provider. For Bitwarden, this uses BW_SESSION
	// from the environment. For 1Password, this triggers system auth.
	session, err := p.Authenticate()
	if err != nil {
		return fmt.Errorf("authentication failed for %s: %w", p.Name(), err)
	}

	// Fetch the list of folders so we can find the one matching the given name.
	folders, err := p.ListFolders(session)
	if err != nil {
		return fmt.Errorf("failed to list folders from %s: %w", p.Name(), err)
	}

	// Find the folder by name (case-sensitive match).
	var targetFolder *provider.Folder
	for _, f := range folders {
		if f.Name == folderName {
			matched := f // Copy to avoid referencing the loop variable.
			targetFolder = &matched
			break
		}
	}

	if targetFolder == nil {
		// Build a helpful error listing available folders.
		available := make([]string, len(folders))
		for i, f := range folders {
			available[i] = f.Name
		}
		return fmt.Errorf("folder %q not found in %s — available folders: %s",
			folderName, p.Name(), strings.Join(available, ", "))
	}

	// Fetch all secrets from the folder.
	secrets, err := p.GetSecrets(session, *targetFolder)
	if err != nil {
		return fmt.Errorf("failed to get secrets from folder %q: %w", folderName, err)
	}

	// Print each secret as an export statement to stdout.
	// direnv will eval this output to set the environment variables.
	for _, s := range secrets {
		// Use proper quoting to handle values with spaces, special chars, etc.
		// We use %q to produce a Go-quoted string which is also valid in bash
		// for most practical purposes.
		fmt.Printf("export %s=%s\n", sanitizeKey(s.Key), shellQuote(s.Value))
	}

	// Print a comment at the end so users can verify how many vars were loaded
	// when running "bwenv export" manually (the comment is harmless in eval).
	fmt.Printf("# bwenv: exported %d variable(s) from %s/%s\n",
		len(secrets), providerSlug, folderName)

	return nil
}

// Remove deletes the .envrc file in the current directory.
// Returns (true, nil) if the file was removed, (false, nil) if it didn't exist,
// or (false, error) if deletion failed.
func Remove() (bool, error) {
	_, err := os.Stat(".envrc")
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("could not check .envrc: %w", err)
	}

	if err := os.Remove(".envrc"); err != nil {
		return false, fmt.Errorf("failed to remove .envrc: %w", err)
	}

	return true, nil
}

// sanitizeKey ensures an environment variable name is valid.
// It replaces any characters that aren't alphanumeric or underscores with underscores.
// Leading digits are also prefixed with an underscore.
func sanitizeKey(key string) string {
	if key == "" {
		return "_EMPTY_KEY"
	}

	var b strings.Builder
	for i, ch := range key {
		switch {
		case ch >= 'A' && ch <= 'Z':
			b.WriteRune(ch)
		case ch >= 'a' && ch <= 'z':
			b.WriteRune(ch)
		case ch >= '0' && ch <= '9':
			// Env var names can't start with a digit — prefix with underscore.
			if i == 0 {
				b.WriteRune('_')
			}
			b.WriteRune(ch)
		case ch == '_':
			b.WriteRune(ch)
		default:
			// Replace any other character with an underscore.
			b.WriteRune('_')
		}
	}

	result := b.String()
	if result == "" {
		return "_EMPTY_KEY"
	}
	return result
}

// shellQuote wraps a value in single quotes for safe use in shell export statements.
// Single quotes in the value are escaped using the standard shell trick:
// end the single-quoted string, add an escaped single quote, start a new single-quoted string.
// Example: "it's" becomes 'it'\”s'
func shellQuote(value string) string {
	// Replace every single quote with the escape sequence.
	escaped := strings.ReplaceAll(value, "'", "'\\''")
	return "'" + escaped + "'"
}

// shellEscape is a simple escaper for provider slugs and other identifiers
// that should only contain safe characters. It removes any shell metacharacters.
func shellEscape(s string) string {
	var b strings.Builder
	for _, ch := range s {
		// Only allow alphanumeric, hyphen, underscore, and dot.
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
			(ch >= '0' && ch <= '9') || ch == '-' || ch == '_' || ch == '.' {
			b.WriteRune(ch)
		}
	}
	return b.String()
}
