// Package envrc handles generating .envrc files and exporting environment
// variables from secret providers. It provides three main capabilities:
//
//  1. Generate() — creates a .envrc file that calls "bwenv export" via direnv.
//  2. Export() — fetches secrets from a provider and prints "export KEY=VALUE"
//     lines to stdout, plus a styled summary to stderr.
//  3. Remove() — deletes the .envrc file from the current directory.
//
// The generated .envrc silences direnv's own noisy output and delegates all
// user-facing feedback to bwenv, so the terminal experience stays clean and
// consistent across all platforms.
package envrc

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/charmbracelet/lipgloss"
	"github.com/s1ks1/bwenv/internal/provider"
)

// -- Styles used for the export summary printed to stderr --

var (
	// summaryBrand is the small "bwenv" tag at the start of the summary line.
	summaryBrand = lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.AdaptiveColor{Light: "#0066CC", Dark: "#58A6FF"})

	// summaryMuted is used for secondary info (provider/folder context).
	summaryMuted = lipgloss.NewStyle().
			Foreground(lipgloss.AdaptiveColor{Light: "#6B7280", Dark: "#9CA3AF"})

	// summarySuccess is the green style for the loaded-variable count.
	summarySuccess = lipgloss.NewStyle().
			Foreground(lipgloss.AdaptiveColor{Light: "#16A34A", Dark: "#4ADE80"})

	// summaryVarName is the style for individual variable names in the list.
	summaryVarName = lipgloss.NewStyle().
			Foreground(lipgloss.AdaptiveColor{Light: "#6B21A8", Dark: "#C084FC"})

	// summaryError is the red style for error messages in the summary.
	summaryError = lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.AdaptiveColor{Light: "#DC2626", Dark: "#F87171"})
)

// Config holds all the parameters needed to generate a .envrc file.
// These are collected during the interactive init flow and written into
// the .envrc so that "bwenv export" can reconstruct the same context
// when direnv loads the file later.
type Config struct {
	// ProviderSlug is the short identifier for the chosen provider (e.g. "bitwarden").
	ProviderSlug string

	// FolderName is the human-readable folder name chosen by the user.
	FolderName string

	// FolderID is the provider-specific unique identifier for the folder.
	// Stored in the .envrc so we don't have to look it up by name every time.
	FolderID string

	// Session is the authentication token (e.g. BW_SESSION for Bitwarden).
	// For providers that manage sessions internally (like 1Password v2), this may be empty.
	Session string

	// Version is the bwenv version that generated this file (for debugging).
	Version string
}

// Generate creates a .envrc file in the current directory. The generated file
// uses direnv's eval mechanism to call "bwenv export", which fetches secrets
// from the configured provider and folder at shell load time.
//
// Key design decisions in the generated .envrc:
//   - DIRENV_LOG_FORMAT is set to "" to silence direnv's own noisy output
//     (like "direnv: export +VAR1 +VAR2..."). bwenv handles all user feedback.
//   - DIRENV_WARN_TIMEOUT uses Go duration format ("10m") which is required
//     by direnv v2.30+ (plain seconds like "600" cause parse errors).
//   - BW_SESSION is stored for Bitwarden users (the token expires, so the
//     user will need to re-run "bwenv init" when it does).
func Generate(cfg Config) error {
	var b strings.Builder

	// -- Header with metadata --
	b.WriteString("# ═══════════════════════════════════════════════════════════════\n")
	b.WriteString(fmt.Sprintf("# Generated by bwenv %s on %s\n",
		cfg.Version, time.Now().Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("# Provider: %s | Folder: %s\n", cfg.ProviderSlug, cfg.FolderName))
	b.WriteString("#\n")
	b.WriteString("# DO NOT edit manually — re-run 'bwenv init' to regenerate.\n")
	b.WriteString("# ═══════════════════════════════════════════════════════════════\n")
	b.WriteString("\n")

	// -- Silence direnv's own output --
	// direnv normally prints noisy messages like "direnv: export +VAR1 +VAR2..."
	// and "direnv: loading .envrc". We silence these because bwenv prints its
	// own styled summary to stderr, giving the user a much cleaner experience.
	b.WriteString("# Silence direnv's default output — bwenv handles all user feedback\n")
	b.WriteString("export DIRENV_LOG_FORMAT=\"\"\n")
	b.WriteString("\n")

	// -- Set a generous timeout --
	// Vault operations (unlock, fetch secrets) can take several seconds.
	// direnv warns after 5s by default and that looks like an error to users.
	// We use Go duration format ("10m") which direnv v2.30+ requires.
	// Plain numbers like "600" cause: "invalid DIRENV_WARN_TIMEOUT: time: missing unit"
	b.WriteString("# Generous timeout for vault operations (direnv v2.30+ needs Go duration format)\n")
	b.WriteString("export DIRENV_WARN_TIMEOUT=\"10m\"\n")
	b.WriteString("\n")

	// -- Bitwarden session token (if applicable) --
	if cfg.Session != "" {
		b.WriteString("# Bitwarden session token (required for vault access)\n")
		b.WriteString("# This token expires — re-run 'bwenv init' if you get auth errors.\n")
		b.WriteString(fmt.Sprintf("export BW_SESSION=%s\n", shellQuote(cfg.Session)))
		b.WriteString("\n")
	}

	// -- The main payload --
	// eval runs "bwenv export" which prints "export KEY=VALUE" lines to stdout.
	// bwenv also prints a styled summary to stderr so the user sees what loaded.
	b.WriteString("# Load secrets from the provider into the environment\n")
	b.WriteString(fmt.Sprintf("eval \"$(bwenv export --provider %s --folder %s)\"\n",
		shellEscape(cfg.ProviderSlug),
		shellQuote(cfg.FolderName),
	))

	// Write the file with restrictive permissions (owner read/write only).
	// The .envrc may contain sensitive data like BW_SESSION tokens.
	if err := os.WriteFile(".envrc", []byte(b.String()), 0600); err != nil {
		return fmt.Errorf("failed to write .envrc: %w", err)
	}

	return nil
}

// AllowDirenv runs "direnv allow" in the current directory so the user
// doesn't have to do it manually after "bwenv init". This prevents the
// scary "direnv: error .envrc is blocked" message from appearing.
//
// If direnv is not installed or the allow command fails, we return an error
// but this should be treated as non-fatal — the user can always run it manually.
func AllowDirenv() error {
	// Check if direnv is available before trying to call it.
	if _, err := exec.LookPath("direnv"); err != nil {
		return fmt.Errorf("direnv not found in PATH")
	}

	cmd := exec.Command("direnv", "allow")
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("'direnv allow' failed: %w", err)
	}

	return nil
}

// Export fetches secrets from the specified provider and folder, then prints
// "export KEY=VALUE" lines to stdout. It also prints a compact, styled summary
// to stderr showing which variables were loaded.
//
// This function is designed to be called from within an .envrc file via eval:
//
//	eval "$(bwenv export --provider bitwarden --folder MyFolder)"
//
// stdout: only "export KEY=VALUE" lines (consumed by eval)
// stderr: styled summary for the user (visible in the terminal)
func Export(providerSlug string, folderName string) error {
	// Look up the requested provider from the registry.
	p, err := provider.Get(providerSlug)
	if err != nil {
		printExportError("Provider not found", err)
		return err
	}

	// Check that the provider's CLI tool is available on this system.
	if !p.IsAvailable() {
		err := fmt.Errorf("'%s' CLI is not installed", p.CLICommand())
		printExportError(fmt.Sprintf("%s unavailable", p.Name()), err)
		return err
	}

	// Authenticate with the provider. For Bitwarden, this uses BW_SESSION
	// from the environment. For 1Password, this triggers system auth.
	session, err := p.Authenticate()
	if err != nil {
		printExportError("Authentication failed", err)
		return fmt.Errorf("authentication failed for %s: %w", p.Name(), err)
	}

	// Fetch the list of folders so we can find the one matching the given name.
	folders, err := p.ListFolders(session)
	if err != nil {
		printExportError("Could not list folders", err)
		return fmt.Errorf("failed to list folders from %s: %w", p.Name(), err)
	}

	// Find the folder by name (case-sensitive match).
	var targetFolder *provider.Folder
	for _, f := range folders {
		if f.Name == folderName {
			matched := f // Copy to avoid referencing the loop variable.
			targetFolder = &matched
			break
		}
	}

	if targetFolder == nil {
		available := make([]string, len(folders))
		for i, f := range folders {
			available[i] = f.Name
		}
		err := fmt.Errorf("folder %q not found — available: %s",
			folderName, strings.Join(available, ", "))
		printExportError("Folder not found", err)
		return err
	}

	// Fetch all secrets from the folder.
	secrets, err := p.GetSecrets(session, *targetFolder)
	if err != nil {
		printExportError("Could not fetch secrets", err)
		return fmt.Errorf("failed to get secrets from folder %q: %w", folderName, err)
	}

	// Collect variable names for the summary (before printing export lines).
	varNames := make([]string, 0, len(secrets))

	// Print each secret as an export statement to stdout.
	// direnv will eval this output to set the environment variables.
	for _, s := range secrets {
		key := sanitizeKey(s.Key)
		fmt.Printf("export %s=%s\n", key, shellQuote(s.Value))
		varNames = append(varNames, key)
	}

	// Print a styled summary to stderr so the user sees what happened.
	// This goes to stderr to avoid polluting the eval'd stdout.
	printExportSummary(p.Name(), folderName, varNames)

	return nil
}

// PreviewSecrets fetches secrets from the given provider and folder and returns
// just the key names (not values). This is used during "bwenv init" to show
// the user what variables will be loaded, without exposing actual secret values.
func PreviewSecrets(p provider.Provider, session string, folder provider.Folder) ([]string, error) {
	secrets, err := p.GetSecrets(session, folder)
	if err != nil {
		return nil, err
	}

	names := make([]string, 0, len(secrets))
	for _, s := range secrets {
		names = append(names, sanitizeKey(s.Key))
	}
	return names, nil
}

// Remove deletes the .envrc file in the current directory.
// Returns (true, nil) if the file was removed, (false, nil) if it didn't exist,
// or (false, error) if deletion failed.
func Remove() (bool, error) {
	_, err := os.Stat(".envrc")
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("could not check .envrc: %w", err)
	}

	if err := os.Remove(".envrc"); err != nil {
		return false, fmt.Errorf("failed to remove .envrc: %w", err)
	}

	return true, nil
}

// ── Export summary output (printed to stderr) ──────────────────────────────

// printExportSummary prints a compact, styled summary of what was loaded.
// This is called at the end of Export() and appears in the user's terminal
// every time direnv loads the .envrc (i.e., when they cd into the directory).
//
// The output is intentionally compact — just 2-3 lines — so it's informative
// without being annoying on repeated loads.
//
// Example output:
//
//	🔐 bwenv · Bitwarden / MySecrets
//	   ✓ 5 variables loaded: API_KEY, DB_URL, SECRET_TOKEN, AWS_KEY, AWS_SECRET
func printExportSummary(providerName string, folderName string, varNames []string) {
	// Line 1: branding + context
	brand := summaryBrand.Render("🔐 bwenv")
	context := summaryMuted.Render(fmt.Sprintf("%s / %s", providerName, folderName))
	fmt.Fprintf(os.Stderr, " %s %s %s\n", brand, summaryMuted.Render("·"), context)

	// Line 2: result
	if len(varNames) == 0 {
		warning := summaryError.Render("⚠  No variables found in this folder")
		fmt.Fprintf(os.Stderr, "    %s\n", warning)
		return
	}

	// Build the variable name list. If there are many variables, truncate
	// the list and show a "+N more" suffix to keep things compact.
	const maxShown = 8
	displayNames := make([]string, 0, len(varNames))
	for i, name := range varNames {
		if i >= maxShown {
			break
		}
		displayNames = append(displayNames, summaryVarName.Render(name))
	}

	varList := strings.Join(displayNames, summaryMuted.Render(", "))
	if len(varNames) > maxShown {
		remaining := len(varNames) - maxShown
		varList += summaryMuted.Render(fmt.Sprintf(" +%d more", remaining))
	}

	count := summarySuccess.Render(fmt.Sprintf("✓ %d variable(s) loaded", len(varNames)))
	fmt.Fprintf(os.Stderr, "    %s: %s\n", count, varList)
}

// printExportError prints a compact error line to stderr during export.
// This replaces the raw error message that would otherwise confuse users
// when direnv loads the .envrc and something goes wrong.
func printExportError(label string, err error) {
	brand := summaryBrand.Render("🔐 bwenv")
	errorLabel := summaryError.Render("✗ " + label)
	detail := summaryMuted.Render(err.Error())
	fmt.Fprintf(os.Stderr, " %s %s %s\n", brand, summaryMuted.Render("·"), errorLabel)
	fmt.Fprintf(os.Stderr, "    %s\n", detail)
}

// ── Shell escaping helpers ─────────────────────────────────────────────────

// sanitizeKey ensures an environment variable name is valid for POSIX shells.
// It replaces any characters that aren't alphanumeric or underscores with
// underscores. Leading digits are prefixed with an underscore since env var
// names can't start with a digit.
func sanitizeKey(key string) string {
	if key == "" {
		return "_EMPTY_KEY"
	}

	var b strings.Builder
	for i, ch := range key {
		switch {
		case ch >= 'A' && ch <= 'Z':
			b.WriteRune(ch)
		case ch >= 'a' && ch <= 'z':
			b.WriteRune(ch)
		case ch >= '0' && ch <= '9':
			if i == 0 {
				b.WriteRune('_') // Env var names can't start with a digit.
			}
			b.WriteRune(ch)
		case ch == '_':
			b.WriteRune(ch)
		default:
			b.WriteRune('_') // Replace any special character with underscore.
		}
	}

	result := b.String()
	if result == "" {
		return "_EMPTY_KEY"
	}
	return result
}

// shellQuote wraps a value in single quotes for safe use in shell export
// statements. Single quotes in the value itself are escaped using the
// standard POSIX shell trick: end the quoted string, add an escaped
// single quote, then start a new quoted string.
//
// Example: it's → 'it'\”s'
func shellQuote(value string) string {
	escaped := strings.ReplaceAll(value, "'", "'\\''")
	return "'" + escaped + "'"
}

// shellEscape strips shell metacharacters from identifiers like provider slugs.
// Only alphanumeric characters, hyphens, underscores, and dots are kept.
func shellEscape(s string) string {
	var b strings.Builder
	for _, ch := range s {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
			(ch >= '0' && ch <= '9') || ch == '-' || ch == '_' || ch == '.' {
			b.WriteRune(ch)
		}
	}
	return b.String()
}
