package envrc

import (
	"os"
	"runtime"
	"strings"
	"testing"
)

const legacyEnvrc = `# Generated by bwenv v2.3.0
# Provider: bitwarden | Folder: Production | Items: API, Database
export DIRENV_LOG_FORMAT=$'\033[2m  \U0001f510 %s\033[0m'
export DIRENV_WARN_TIMEOUT="10m"
export BW_SESSION='migration-session-secret'
eval "$(bwenv export --provider bitwarden --folder 'Production' --items 'item-api,item-db')"
`

func setupLegacyProject(t *testing.T, content string) {
	t.Helper()
	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(originalDir) })
	if err := os.WriteFile(".envrc", []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
}

func TestMigrateProjectDryRunMakesNoChanges(t *testing.T) {
	setupLegacyProject(t, legacyEnvrc)
	result, err := MigrateProject(true)
	if err != nil {
		t.Fatalf("MigrateProject(true) returned error: %v", err)
	}
	if !strings.Contains(result, "No files changed") || strings.Contains(result, "migration-session-secret") {
		t.Fatalf("unexpected or sensitive dry-run output: %q", result)
	}
	if _, err := os.Stat(".bwenv.toml"); !os.IsNotExist(err) {
		t.Fatalf("dry-run created .bwenv.toml: %v", err)
	}
	if _, err := os.Stat(migrationBackupPath); !os.IsNotExist(err) {
		t.Fatalf("dry-run created a backup: %v", err)
	}
	original, err := os.ReadFile(".envrc")
	if err != nil {
		t.Fatal(err)
	}
	if string(original) != legacyEnvrc {
		t.Fatal("dry-run changed the original .envrc")
	}
}

func TestMigrateProjectPreservesBehaviorAndBackup(t *testing.T) {
	setupLegacyProject(t, legacyEnvrc)
	result, err := MigrateProject(false)
	if err != nil {
		t.Fatalf("MigrateProject(false) returned error: %v", err)
	}
	if strings.Contains(result, "migration-session-secret") {
		t.Fatal("migration output exposed the session token")
	}
	configData, err := os.ReadFile(".bwenv.toml")
	if err != nil {
		t.Fatalf("read migrated project config: %v", err)
	}
	if strings.Contains(string(configData), "migration-session-secret") {
		t.Fatal("project config contains the session token")
	}
	projectConfig, err := LoadProjectConfig(".bwenv.toml")
	if err != nil {
		t.Fatalf("migrated project config is invalid: %v", err)
	}
	if projectConfig.Provider != "bitwarden" || projectConfig.Project.FolderName != "Production" || len(projectConfig.Project.Items) != 2 {
		t.Fatalf("legacy metadata was not preserved: %+v", projectConfig)
	}
	activation, err := os.ReadFile(".envrc")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(activation), "bwenv export --project .") || !strings.Contains(string(activation), "BW_SESSION='migration-session-secret'") {
		t.Fatal("migration did not preserve project activation and the current v2 session behavior")
	}
	if !strings.Contains(string(activation), generatedDirenvLogFormat) || !strings.Contains(string(activation), generatedDirenvTimeout) {
		t.Fatal("migration did not preserve generated direnv settings")
	}
	if strings.Contains(string(activation), "--provider") || strings.Contains(string(activation), "--items") {
		t.Fatal("migrated .envrc still duplicates project metadata")
	}
	backup, err := os.ReadFile(migrationBackupPath)
	if err != nil {
		t.Fatalf("read migration backup: %v", err)
	}
	if string(backup) != legacyEnvrc {
		t.Fatal("migration backup does not match the original .envrc")
	}
	if runtime.GOOS != "windows" {
		for _, name := range []string{migrationBackupPath, ".envrc"} {
			info, err := os.Stat(name)
			if err != nil {
				t.Fatal(err)
			}
			if info.Mode().Perm() != 0600 {
				t.Errorf("%s permissions = %o; want 600", name, info.Mode().Perm())
			}
		}
	}
}

func TestUnquoteShellValue(t *testing.T) {
	tests := []struct {
		value string
		want  string
		ok    bool
	}{
		{value: `'token'`, want: "token", ok: true},
		{value: `'it'\''s'`, want: "it's", ok: true},
		{value: `"token"`},
		{value: `$(command)`},
		{value: `'unfinished`},
	}
	for _, tt := range tests {
		got, ok := unquoteShellValue(tt.value)
		if got != tt.want || ok != tt.ok {
			t.Errorf("unquoteShellValue(%q) = (%q, %t), want (%q, %t)", tt.value, got, ok, tt.want, tt.ok)
		}
	}
}

func TestMigrateProjectRejectsCustomShellCodeWithoutChanges(t *testing.T) {
	original := legacyEnvrc + "export CUSTOM_VALUE=keep-me\n"
	setupLegacyProject(t, original)
	if _, err := MigrateProject(false); err == nil {
		t.Fatal("expected custom shell code to require manual migration")
	}
	content, err := os.ReadFile(".envrc")
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != original {
		t.Fatal("failed migration changed the original .envrc")
	}
	for _, name := range []string{".bwenv.toml", migrationBackupPath} {
		if _, err := os.Stat(name); !os.IsNotExist(err) {
			t.Errorf("failed migration left %s behind: %v", name, err)
		}
	}
}
