// Package mise is the experimental activation backend for users already on
// mise. It stays a thin adapter: mise sources a small script that delegates
// retrieval to bwenv, so provider logic never moves into mise.
//
// Flow: mise -> .bwenv.mise.sh -> bwenv export -> provider.
package mise

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/pelletier/go-toml/v2"

	"github.com/s1ks1/bwenv/v3/internal/activation"
	"github.com/s1ks1/bwenv/v3/internal/project"
)

const (
	// scriptPath is the bash script mise sources (env._.source).
	scriptPath = ".bwenv.mise.sh"
	// configPath is the mise configuration file.
	configPath = "mise.toml"
	// marker identifies the bwenv block in mise.toml.
	marker                = "# bwenv activation (experimental)"
	sourceDirective       = `_.source = { path = ".bwenv.mise.sh", tools = true }`
	legacySourceDirective = `_.source = ".bwenv.mise.sh"`
)

// script is sourced by mise; mise pulls the exported variables out of it.
//
// mise re-evaluates this script on prompts, so the exported values are cached
// under $XDG_CACHE_HOME/bwenv/mise and refreshed only when .bwenv.toml is newer
// than the cache or the TTL (BWENV_MISE_TTL_MIN, default 60) expires. This keeps
// prompts fast: bw runs at most once per TTL instead of on every prompt.
// Set BWENV_MISE_TTL_MIN=0 to always refresh.
const script = `#!/usr/bin/env bash
# Generated by bwenv. Do not edit by hand — re-run 'bwenv init --activation mise'.
root="$(dirname "${BASH_SOURCE[0]}")"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/bwenv/mise"
key="$(printf '%s' "$root" | cksum | awk '{print $1}')"
cache="$cache_dir/$key.env"
sess="$(printf '%s' "${BW_SESSION:-}" | cksum | awk '{print $1}')"

refresh=1
if [ -f "$cache" ]; then
  cached_sess="$(sed -n '1s/^# session //p' "$cache" 2>/dev/null)"
  if [ "$cached_sess" = "$sess" ] && [ -f "$root/.bwenv.toml" ] && [ "$cache" -nt "$root/.bwenv.toml" ]; then
    ttl="${BWENV_MISE_TTL_MIN:-60}"
    if [ "$ttl" -gt 0 ] && [ -n "$(find "$cache" -mmin -"$ttl" 2>/dev/null)" ]; then
      refresh=0
    fi
  fi
fi

if [ "$refresh" -eq 1 ]; then
  mkdir -p "$cache_dir" 2>/dev/null
  if out="$(command bwenv export --quiet --project "$root" 2>/dev/null)"; then
    ( umask 077 && { printf '# session %s\n' "$sess"; printf '%s\n' "$out"; } > "$cache" ) 2>/dev/null
    unset _BWENV_LOGIN_REQUIRED
    # shellcheck disable=SC1090
    . "$cache"
  elif [ "$?" -eq 2 ]; then
    export _BWENV_LOGIN_REQUIRED="$root"
  else
    unset _BWENV_LOGIN_REQUIRED
  fi
else
  unset _BWENV_LOGIN_REQUIRED
  # shellcheck disable=SC1090
  . "$cache"
fi
`

// Activator is the mise activation backend.
type Activator struct{}

func init() { activation.Register(&Activator{}) }

// Name is the activation.mode value that selects this backend.
func (a *Activator) Name() string { return "mise" }

// Available reports whether the mise CLI is installed.
func (a *Activator) Available() bool {
	_, err := exec.LookPath("mise")
	return err == nil
}

// Detect reports whether mise is installed and the project is wired for it.
func (a *Activator) Detect() activation.Status {
	status := activation.Status{Installed: a.Available()}
	if _, err := os.Stat(scriptPath); err == nil {
		status.Configured = true
	}
	switch {
	case !status.Installed:
		status.Detail = "mise is not installed"
	case !status.Configured:
		status.Detail = "no " + scriptPath + " in this directory"
	default:
		status.Detail = scriptPath + " present"
	}
	return status
}

// Render returns the sourced script that delegates retrieval to bwenv.
func (a *Activator) Render(activation.Config) ([]byte, error) {
	return []byte(script), nil
}

// Install preserves existing mise settings and adds only the bwenv source directive.
func (a *Activator) Install(cfg activation.Config) error {
	if err := (project.Config{Version: project.ConfigVersion, Provider: cfg.ProviderSlug, Project: project.Metadata{FolderName: cfg.FolderName}, Activation: project.Activation{Mode: "mise"}}).Validate(); err != nil {
		return err
	}
	content, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", configPath, err)
	}
	var config struct {
		Env map[string]any `toml:"env"`
	}
	if err := toml.Unmarshal(content, &config); err != nil {
		return fmt.Errorf("parse %s: %w", configPath, err)
	}
	configured := false
	changed := false
	if directives, ok := config.Env["_"].(map[string]any); ok {
		if source, exists := directives["source"]; exists {
			switch source := source.(type) {
			case string:
				if source != scriptPath || !strings.Contains(string(content), legacySourceDirective) {
					return fmt.Errorf("%s already has env._.source; include %s with tools = true manually", configPath, scriptPath)
				}
				content = []byte(strings.Replace(string(content), legacySourceDirective, sourceDirective, 1))
				changed = true
			case map[string]any:
				if source["path"] != scriptPath || source["tools"] != true {
					return fmt.Errorf("%s: bwenv source requires path = %q and tools = true", configPath, scriptPath)
				}
			default:
				return fmt.Errorf("%s already has env._.source; include %s with tools = true manually", configPath, scriptPath)
			}
			configured = true
		}
	}
	if !configured {
		block := marker + "\n" + sourceDirective + "\n"
		header := regexp.MustCompile(`(?m)^\s*\[env\]\s*(?:#.*)?$`)
		if location := header.FindIndex(content); location != nil {
			content = []byte(string(content[:location[1]]) + "\n" + block + string(content[location[1]:]))
		} else if config.Env == nil {
			content = append(content, []byte("\n[env]\n"+block)...)
		} else {
			return fmt.Errorf("add env._.source = %q to %s manually", scriptPath, configPath)
		}
	}
	if err := os.WriteFile(scriptPath, []byte(script), 0600); err != nil {
		return err
	}
	if !configured || changed {
		if err := os.WriteFile(configPath, content, 0644); err != nil {
			return err
		}
	}
	return activation.WriteProject(cfg, a.Name())
}

// Remove deletes only generated artifacts; unrelated mise settings are preserved.
func (a *Activator) Remove() error {
	content, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	block := marker + "\n" + sourceDirective + "\n"
	if !strings.Contains(string(content), block) {
		block = marker + "\n" + legacySourceDirective + "\n"
	}
	if strings.Contains(string(content), block) {
		remaining := strings.Replace(string(content), block, "", 1)
		if strings.TrimSpace(remaining) == "[env]" {
			if err := os.Remove(configPath); err != nil {
				return err
			}
		} else if err := os.WriteFile(configPath, []byte(remaining), 0644); err != nil {
			return err
		}
	}
	if err := os.Remove(scriptPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// Resolve reads the canonical project config for the provider source.
func (a *Activator) Resolve() (activation.Source, error) {
	cfg, err := project.Load(".bwenv.toml")
	if err != nil {
		return activation.Source{}, err
	}
	return activation.Source{
		ProviderSlug: cfg.Provider,
		FolderName:   cfg.Project.FolderName,
		FolderID:     cfg.Project.FolderID,
		ItemIDs:      cfg.Project.Items,
	}, nil
}

// Approve and Unapprove are no-ops: mise manages its own shell hook.
func (a *Activator) Approve() error   { return nil }
func (a *Activator) Unapprove() error { return nil }

// Reload drops the cached env so the next prompt refetches the secrets. It is
// what 'bwenv refresh' triggers for a mise project.
func (a *Activator) Reload() error {
	dir := miseCacheDir()
	if dir == "" {
		return nil
	}
	if err := os.RemoveAll(dir); err != nil {
		return fmt.Errorf("clear mise env cache: %w", err)
	}
	return nil
}

// miseCacheDir is the shared cache directory the generated script writes to.
func miseCacheDir() string {
	if xdg := os.Getenv("XDG_CACHE_HOME"); xdg != "" {
		return filepath.Join(xdg, "bwenv", "mise")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".cache", "bwenv", "mise")
}
