// Package mise is the experimental activation backend for users already on
// mise. It stays a thin adapter: mise sources a small script that delegates
// retrieval to bwenv, so provider logic never moves into mise.
//
// Flow: mise -> .bwenv.mise.sh -> bwenv export -> provider.
package mise

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/s1ks1/bwenv/v3/internal/activation"
	"github.com/s1ks1/bwenv/v3/internal/project"
)

const (
	// scriptPath is the bash script mise sources (env._.source).
	scriptPath = ".bwenv.mise.sh"
	// configPath is the mise configuration file.
	configPath = "mise.toml"
	// marker identifies the bwenv block in mise.toml.
	marker = "# bwenv activation (experimental)"
)

// script is sourced by mise; mise pulls the exported variables out of it.
const script = `#!/usr/bin/env bash
# Generated by bwenv. Do not edit by hand — re-run 'bwenv init --activation mise'.
# mise sources this script; all secret retrieval stays inside bwenv.
eval "$(bwenv export --project .)"
`

// Activator is the mise activation backend.
type Activator struct{}

func init() { activation.Register(&Activator{}) }

// Name is the activation.mode value that selects this backend.
func (a *Activator) Name() string { return "mise" }

// Available reports whether the mise CLI is installed.
func (a *Activator) Available() bool {
	_, err := exec.LookPath("mise")
	return err == nil
}

// Detect reports whether mise is installed and the project is wired for it.
func (a *Activator) Detect() activation.Status {
	status := activation.Status{Installed: a.Available()}
	if _, err := os.Stat(scriptPath); err == nil {
		status.Configured = true
	}
	switch {
	case !status.Installed:
		status.Detail = "mise is not installed"
	case !status.Configured:
		status.Detail = "no " + scriptPath + " in this directory"
	default:
		status.Detail = scriptPath + " present"
	}
	return status
}

// Render returns the sourced script that delegates retrieval to bwenv.
func (a *Activator) Render(activation.Config) ([]byte, error) {
	return []byte(script), nil
}

// Install writes the sourced script and, when mise.toml does not exist yet, a
// minimal mise config that sources it. An existing mise.toml is never modified:
// the required snippet is reported instead, because rewriting a user's mise
// config could clobber unrelated settings.
func (a *Activator) Install(activation.Config) error {
	if err := os.WriteFile(scriptPath, []byte(script), 0600); err != nil {
		return fmt.Errorf("write %s: %w", scriptPath, err)
	}

	content, err := os.ReadFile(configPath)
	switch {
	case os.IsNotExist(err):
		block := marker + "\n[env]\n_.source = \"" + scriptPath + "\"\n"
		if err := os.WriteFile(configPath, []byte(block), 0644); err != nil {
			return fmt.Errorf("write %s: %w", configPath, err)
		}
		return nil
	case err != nil:
		return fmt.Errorf("read %s: %w", configPath, err)
	case strings.Contains(string(content), marker):
		return nil // already configured
	default:
		return fmt.Errorf("%s already exists; add this block manually:\n\n%s\n[env]\n_.source = %q", configPath, marker, scriptPath)
	}
}

// Remove deletes the sourced script. It leaves mise.toml untouched.
func (a *Activator) Remove() error {
	if err := os.Remove(scriptPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove %s: %w", scriptPath, err)
	}
	return nil
}

// Resolve reads the canonical project config for the provider source.
func (a *Activator) Resolve() (activation.Source, error) {
	cfg, err := project.Load(".bwenv.toml")
	if err != nil {
		return activation.Source{}, err
	}
	return activation.Source{
		ProviderSlug: cfg.Provider,
		FolderName:   cfg.Project.FolderName,
		FolderID:     cfg.Project.FolderID,
		ItemIDs:      cfg.Project.Items,
	}, nil
}

// Approve, Unapprove and Reload are no-ops: mise manages its own shell hook and
// reloads when the project config changes.
func (a *Activator) Approve() error   { return nil }
func (a *Activator) Unapprove() error { return nil }
func (a *Activator) Reload() error    { return nil }
