// Package mise is the experimental activation backend for users already on
// mise. It stays a thin adapter: mise sources a small script that delegates
// retrieval to bwenv, so provider logic never moves into mise.
//
// Flow: mise -> .bwenv.mise.sh -> bwenv export -> provider.
package mise

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/pelletier/go-toml/v2"

	"github.com/s1ks1/bwenv/v3/internal/activation"
	"github.com/s1ks1/bwenv/v3/internal/project"
)

const (
	// scriptPath is the bash script mise sources (env._.source).
	scriptPath = ".bwenv.mise.sh"
	// configPath is the mise configuration file.
	configPath = "mise.toml"
	// marker identifies the bwenv block in mise.toml.
	marker                = "# bwenv activation (experimental)"
	sourceDirective       = `_.source = { path = ".bwenv.mise.sh", tools = true }`
	legacySourceDirective = `_.source = ".bwenv.mise.sh"`
)

// script is sourced by mise. Secret values remain in memory; the parent
// shell shows a login hint once per project entry when authentication expires.
const script = `#!/usr/bin/env bash
# Generated by bwenv. Do not edit by hand — re-run 'bwenv init --activation mise'.
_bwenv_root="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
if _bwenv_exports="$(command bwenv export --quiet --project "$_bwenv_root")"; then
  eval "$_bwenv_exports"
  unset _BWENV_LOGIN_REQUIRED
elif [ "$?" -eq 2 ]; then
  export _BWENV_LOGIN_REQUIRED="$_bwenv_root"
else
  unset _BWENV_LOGIN_REQUIRED
fi
unset _bwenv_exports _bwenv_root
`

// Activator is the mise activation backend.
type Activator struct{}

func init() { activation.Register(&Activator{}) }

// Name is the activation.mode value that selects this backend.
func (a *Activator) Name() string { return "mise" }

// Available reports whether the mise CLI is installed.
func (a *Activator) Available() bool {
	_, err := exec.LookPath("mise")
	return err == nil
}

// Detect reports whether mise is installed and the project is wired for it.
func (a *Activator) Detect() activation.Status {
	status := activation.Status{Installed: a.Available()}
	if _, err := os.Stat(scriptPath); err == nil {
		status.Configured = true
	}
	switch {
	case !status.Installed:
		status.Detail = "mise is not installed"
	case !status.Configured:
		status.Detail = "no " + scriptPath + " in this directory"
	default:
		status.Detail = scriptPath + " present"
	}
	return status
}

// Render returns the sourced script that delegates retrieval to bwenv.
func (a *Activator) Render(activation.Config) ([]byte, error) {
	return []byte(script), nil
}

// Install preserves existing mise settings and adds only the bwenv source directive.
func (a *Activator) Install(cfg activation.Config) error {
	if err := (project.Config{Version: project.ConfigVersion, Provider: cfg.ProviderSlug, Project: project.Metadata{FolderName: cfg.FolderName}, Activation: project.Activation{Mode: "mise"}}).Validate(); err != nil {
		return err
	}
	content, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", configPath, err)
	}
	var config struct {
		Env map[string]any `toml:"env"`
	}
	if err := toml.Unmarshal(content, &config); err != nil {
		return fmt.Errorf("parse %s: %w", configPath, err)
	}
	configured := false
	changed := false
	if directives, ok := config.Env["_"].(map[string]any); ok {
		if source, exists := directives["source"]; exists {
			switch source := source.(type) {
			case string:
				if source != scriptPath || !strings.Contains(string(content), legacySourceDirective) {
					return fmt.Errorf("%s already has env._.source; include %s with tools = true manually", configPath, scriptPath)
				}
				content = []byte(strings.Replace(string(content), legacySourceDirective, sourceDirective, 1))
				changed = true
			case map[string]any:
				if source["path"] != scriptPath || source["tools"] != true {
					return fmt.Errorf("%s: bwenv source requires path = %q and tools = true", configPath, scriptPath)
				}
			default:
				return fmt.Errorf("%s already has env._.source; include %s with tools = true manually", configPath, scriptPath)
			}
			configured = true
		}
	}
	if !configured {
		block := marker + "\n" + sourceDirective + "\n"
		header := regexp.MustCompile(`(?m)^\s*\[env\]\s*(?:#.*)?$`)
		if location := header.FindIndex(content); location != nil {
			content = []byte(string(content[:location[1]]) + "\n" + block + string(content[location[1]:]))
		} else if config.Env == nil {
			content = append(content, []byte("\n[env]\n"+block)...)
		} else {
			return fmt.Errorf("add env._.source = %q to %s manually", scriptPath, configPath)
		}
	}
	// Remove caches from older generated scripts before installing this version.
	if err := a.Reload(); err != nil {
		return err
	}
	if err := os.WriteFile(scriptPath, []byte(script), 0600); err != nil {
		return err
	}
	if !configured || changed {
		if err := os.WriteFile(configPath, content, 0644); err != nil {
			return err
		}
	}
	return activation.WriteProject(cfg, a.Name())
}

// Remove deletes only generated artifacts; unrelated mise settings are preserved.
func (a *Activator) Remove() error {
	content, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	block := marker + "\n" + sourceDirective + "\n"
	if !strings.Contains(string(content), block) {
		block = marker + "\n" + legacySourceDirective + "\n"
	}
	if strings.Contains(string(content), block) {
		remaining := strings.Replace(string(content), block, "", 1)
		if strings.TrimSpace(remaining) == "[env]" {
			if err := os.Remove(configPath); err != nil {
				return err
			}
		} else if err := os.WriteFile(configPath, []byte(remaining), 0644); err != nil {
			return err
		}
	}
	if err := os.Remove(scriptPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// Resolve reads the canonical project config for the provider source.
func (a *Activator) Resolve() (activation.Source, error) {
	return activation.ResolveFromProjectConfig()
}

// Approval is stored in canonical metadata; mise keeps managing its shell hook.
func (a *Activator) Approve() error   { return project.SetDisabled(".bwenv.toml", false) }
func (a *Activator) Unapprove() error { return project.SetDisabled(".bwenv.toml", true) }

// Reload removes legacy plaintext caches. The generated script always fetches
// into memory; a future warm cache belongs in the optional secure agent.
func (a *Activator) Reload() error {
	dir := miseCacheDir()
	if dir != "" {
		if err := os.RemoveAll(dir); err != nil {
			return fmt.Errorf("clear legacy mise cache: %w", err)
		}
	}
	current, err := os.ReadFile(scriptPath)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read mise script: %w", err)
	}
	if strings.HasPrefix(string(current), "#!/usr/bin/env bash\n# Generated by bwenv.") && string(current) != script {
		if err := os.WriteFile(scriptPath, []byte(script), 0600); err != nil {
			return fmt.Errorf("upgrade generated mise script: %w", err)
		}
	}
	return nil
}

// miseCacheDir identifies the legacy plaintext cache, retained only for cleanup.
func miseCacheDir() string {
	if xdg := os.Getenv("XDG_CACHE_HOME"); xdg != "" {
		return filepath.Join(xdg, "bwenv", "mise")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".cache", "bwenv", "mise")
}
