package mise

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/s1ks1/bwenv/v3/internal/activation"
	"github.com/s1ks1/bwenv/v3/internal/project"
)

func TestActivatorBasics(t *testing.T) {
	a := &Activator{}
	if a.Name() != "mise" {
		t.Fatalf("Name() = %q, want mise", a.Name())
	}

	content, err := a.Render(activation.Config{})
	if err != nil {
		t.Fatalf("Render() error: %v", err)
	}
	if !strings.Contains(string(content), "bwenv export --quiet --project") {
		t.Fatalf("Render() must delegate to bwenv:\n%s", content)
	}

	got, err := activation.Get("mise")
	if err != nil || got.Name() != "mise" {
		t.Fatalf("mise backend not registered: %v", err)
	}
}

func TestInstallWritesDelegatingConfig(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	a := &Activator{}
	if err := a.Install(activation.Config{ProviderSlug: "bitwarden", FolderName: "Team", FolderID: "folder-1"}); err != nil {
		t.Fatalf("Install() error: %v", err)
	}

	if _, err := os.Stat(scriptPath); err != nil {
		t.Fatalf("Install() must write %s: %v", scriptPath, err)
	}
	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("Install() must write %s: %v", configPath, err)
	}
	if !strings.Contains(string(data), sourceDirective) {
		t.Fatalf("%s does not source the script:\n%s", configPath, data)
	}

	// Idempotent: a second install keeps a single bwenv block.
	if err := a.Install(activation.Config{ProviderSlug: "bitwarden", FolderName: "Team", FolderID: "folder-1"}); err != nil {
		t.Fatalf("second Install() error: %v", err)
	}
	again, _ := os.ReadFile(configPath)
	if n := strings.Count(string(again), marker); n != 1 {
		t.Fatalf("expected one marker, got %d", n)
	}
}

func TestInstallPreservesExistingMiseConfig(t *testing.T) {
	for _, content := range []string{"[tools]\nnode = \"20\"\n", "[env]\nEXISTING = \"value\"\n[tools]\nnode = \"20\"\n"} {
		t.Run(content, func(t *testing.T) {
			t.Chdir(t.TempDir())
			t.Setenv("XDG_CACHE_HOME", t.TempDir())
			if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
				t.Fatal(err)
			}
			a := &Activator{}
			if err := a.Install(activation.Config{ProviderSlug: "bitwarden", FolderName: "Team"}); err != nil {
				t.Fatal(err)
			}
			if _, err := project.Load("."); err != nil {
				t.Fatal(err)
			}
			if err := a.Remove(); err != nil {
				t.Fatal(err)
			}
			remaining, err := os.ReadFile(configPath)
			if err != nil || !strings.Contains(string(remaining), "node = \"20\"") || strings.Contains(string(remaining), "_.source") {
				t.Fatalf("remove did not preserve config: %s, %v", remaining, err)
			}
		})
	}
}

func TestResolveReadsProjectConfig(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	if err := project.Write(".bwenv.toml", project.Config{
		Version:    project.ConfigVersion,
		Provider:   "bitwarden",
		Project:    project.Metadata{FolderName: "Team", FolderID: "folder-1"},
		Activation: project.Activation{Mode: "mise"},
	}); err != nil {
		t.Fatal(err)
	}

	src, err := (&Activator{}).Resolve()
	if err != nil {
		t.Fatalf("Resolve() error: %v", err)
	}
	if src.ProviderSlug != "bitwarden" || src.FolderName != "Team" {
		t.Fatalf("Resolve() = %+v", src)
	}
}

func chdir(t *testing.T, dir string) {
	t.Helper()
	t.Setenv("XDG_CACHE_HOME", t.TempDir())
	orig, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(orig) })
}

func TestReloadClearsLegacyCachedEnv(t *testing.T) {
	xdg := t.TempDir()
	t.Setenv("XDG_CACHE_HOME", xdg)

	cacheDir := filepath.Join(xdg, "bwenv", "mise")
	if err := os.MkdirAll(cacheDir, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(cacheDir, "proj.env"), []byte("API_KEY=value\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := (&Activator{}).Reload(); err != nil {
		t.Fatalf("Reload() error: %v", err)
	}
	if _, err := os.Stat(cacheDir); !os.IsNotExist(err) {
		t.Fatalf("Reload() must clear the mise env cache, stat error: %v", err)
	}
}

func TestReloadUpgradesGeneratedScriptsAndPreservesCustomScripts(t *testing.T) {
	t.Chdir(t.TempDir())
	t.Setenv("XDG_CACHE_HOME", t.TempDir())
	for _, content := range []string{"#!/usr/bin/env bash\n# Generated by bwenv.\n# legacy script\n", "# custom script\nexport CUSTOM=value\n"} {
		if err := os.WriteFile(scriptPath, []byte(content), 0600); err != nil {
			t.Fatal(err)
		}
		if err := (&Activator{}).Reload(); err != nil {
			t.Fatal(err)
		}
		got, err := os.ReadFile(scriptPath)
		if err != nil {
			t.Fatal(err)
		}
		want := content
		if strings.Contains(content, "# Generated by bwenv.") {
			want = script
		}
		if string(got) != want {
			t.Fatal("refresh failed to upgrade generated script or changed a custom script")
		}
	}
}

func TestInstallUpgradesLegacySourceAfterTools(t *testing.T) {
	t.Setenv("XDG_CACHE_HOME", t.TempDir())
	t.Chdir(t.TempDir())
	legacy := "[tools]\nnode = \"23\"\n[env]\nKEEP = \"value\"\n" + marker + "\n" + legacySourceDirective + "\n"
	if err := os.WriteFile(configPath, []byte(legacy), 0644); err != nil {
		t.Fatal(err)
	}
	a := &Activator{}
	cfg := activation.Config{ProviderSlug: "bitwarden", FolderName: "Team"}
	if err := a.Install(cfg); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(configPath)
	if err != nil || !strings.Contains(string(data), sourceDirective) || !strings.Contains(string(data), "KEEP = \"value\"") {
		t.Fatalf("legacy source not upgraded safely: %s, %v", data, err)
	}
	if err := a.Install(cfg); err != nil {
		t.Fatal(err)
	}
	again, _ := os.ReadFile(configPath)
	if string(data) != string(again) {
		t.Fatal("upgrade not idempotent")
	}
}
