package ui

import (
	"io"
	"os"
	"runtime"
	"strings"
	"testing"
)

func TestCheckEnvrcStatusReadsFolderIDWithoutRetainingContents(t *testing.T) {
	oldDir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(oldDir) })

	const secret = "DO_NOT_REPORT_THIS_TOKEN"
	content := "# Generated by bwenv\n# Provider: bitwarden | Folder: Dev\neval \"$(bwenv export --provider bitwarden --folder-id 'folder-123')\"\nexport API_TOKEN=" + secret + "\n"
	if err := os.WriteFile(".envrc", []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	info := checkEnvrcStatus()
	if info.state != envrcBwenv || info.provider != "bitwarden" || info.folderID != "folder-123" {
		t.Fatalf("unexpected parsed diagnostics: %#v", info)
	}
	if info.folder != "Dev" {
		t.Fatalf("expected parsed configuration metadata: %#v", info)
	}
	if strings.Contains(info.provider+info.folder+info.folderID, secret) {
		t.Fatal("diagnostics retained secret content")
	}
}

func TestFileHasPrivatePermissions(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Unix permission bits are not meaningful on Windows")
	}
	path := t.TempDir() + "/.envrc"
	if err := os.WriteFile(path, []byte("safe"), 0600); err != nil {
		t.Fatal(err)
	}
	if !fileHasPrivatePermissions(path) {
		t.Fatal("expected mode 0600 to be private")
	}
	if err := os.Chmod(path, 0644); err != nil {
		t.Fatal(err)
	}
	if fileHasPrivatePermissions(path) {
		t.Fatal("expected mode 0644 to be non-private")
	}
}

func TestRunDoctorFlowDoesNotPrintEnvrcContents(t *testing.T) {
	oldDir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(oldDir) })
	t.Setenv("PATH", t.TempDir())

	const secret = "DO_NOT_REPORT_THIS_TOKEN"
	content := "# Generated by bwenv\n# Provider: bitwarden | Folder: Dev\neval \"$(bwenv export --provider bitwarden --folder-id 'folder-123')\"\nexport API_TOKEN=" + secret + "\n"
	if err := os.WriteFile(".envrc", []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	reader, writer, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	oldStdout := os.Stdout
	os.Stdout = writer
	flowErr := RunDoctorFlow("test")
	_ = writer.Close()
	os.Stdout = oldStdout
	output, readErr := io.ReadAll(reader)
	_ = reader.Close()
	if readErr != nil {
		t.Fatal(readErr)
	}
	if flowErr == nil {
		t.Fatal("expected missing dependencies to fail diagnostics")
	}
	if strings.Contains(string(output), secret) {
		t.Fatal("doctor output included .envrc contents")
	}
	if !strings.Contains(string(output), "FolderID fast path configured") {
		t.Fatal("doctor output did not report the configured FolderID fast path")
	}
}
