// Package ui — status flow for showing current bwenv state at a glance.
// This file implements "bwenv status", a detailed overview of active sessions,
// .envrc presence, config state, and provider availability.
package ui

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/charmbracelet/lipgloss"
	"github.com/s1ks1/bwenv/v3/internal/activation"
	"github.com/s1ks1/bwenv/v3/internal/config"
	"github.com/s1ks1/bwenv/v3/internal/provider"
)

// RunStatusFlow displays a comprehensive status overview of the current bwenv state.
// This combines the previous "status" and "test" commands into one detailed view:
//
//  1. Current directory & .envrc status
//  2. Core dependencies (direnv)
//  3. Provider availability and sessions
//  4. Direnv hook configuration
//  5. Relevant environment variables
//  6. Current config preferences
func RunStatusFlow(version string) error {
	ctx := context.Background()
	PrintBanner(version)
	fmt.Println()

	// ── Section: Current directory & project ──────────────────────────────
	printStatusSection(E("📂", "[>]") + " Current Directory")

	cwd, err := os.Getwd()
	if err != nil {
		PrintWarningLine("Working directory", "could not determine")
	} else {
		shortCwd := ShortenHomePath(cwd)
		PrintKeyValue("Directory", shortCwd)
	}

	// Check for canonical project metadata or a legacy generated .envrc.
	envrcStatus := checkEnvrcStatus()
	switch envrcStatus.state {
	case envrcMissing:
		PrintStatusLine(false, "Project", "no .bwenv.toml or bwenv .envrc — run 'bwenv init'")
	case envrcPresent:
		PrintStatusLine(true, ".envrc", E("📄", "->")+" found (not generated by bwenv)")
	case envrcBwenv:
		detail := fmt.Sprintf("%s bwenv-managed", E("📄", "->"))
		name := ".envrc"
		if envrcStatus.canonical {
			name = ".bwenv.toml"
		}
		if envrcStatus.activation != "" {
			detail += " | activation: " + envrcStatus.activation
		}
		if envrcStatus.provider != "" {
			detail += fmt.Sprintf(" | provider: %s", envrcStatus.provider)
		}
		if envrcStatus.folder != "" {
			detail += fmt.Sprintf(" | folder: %s", envrcStatus.folder)
		}
		if len(envrcStatus.itemIDs) > 0 {
			detail += fmt.Sprintf(" | items: %d selected", len(envrcStatus.itemIDs))
		}
		PrintStatusLine(true, name, detail)
	case envrcInvalid:
		name := ".envrc"
		if envrcStatus.canonical {
			name = ".bwenv.toml"
		}
		PrintStatusLine(false, name, envrcStatus.problem)
	}

	fmt.Println()

	// ── Section: Core dependencies ──────────────────────────────────────
	printStatusSection(E("📦", "[>]") + " Dependencies")

	if activator, err := activation.ForProject(); err != nil {
		PrintStatusLine(false, "activation config", err.Error())
	} else if activator.Name() == "direnv" {
		if direnvPath, lookErr := exec.LookPath("direnv"); lookErr == nil {
			PrintStatusLine(true, "direnv", direnvPath)
		} else {
			PrintStatusLine(false, "direnv", "not found — install from https://direnv.net/")
		}
		checkDirenvHook()
	} else {
		status := activator.Detect()
		PrintStatusLine(status.Installed, activator.Name(), status.Detail)
	}

	fmt.Println()

	// ── Section: Provider sessions ───────────────────────────────────────
	printStatusSection(E("🔑", "[>]") + " Providers")

	allProviders := provider.All()
	if len(allProviders) == 0 {
		PrintWarningLine("Providers", "no providers registered (this is a bug)")
	} else {
		activeCount := 0
		availableCount := 0
		for _, p := range allProviders {
			if !p.IsAvailable() {
				PrintStatusLine(false, p.Name(),
					fmt.Sprintf("'%s' not installed", p.CLICommand()))
				continue
			}

			availableCount++

			authenticated := false
			if auth, authErr := provider.AsAuthenticator(p); authErr == nil {
				authenticated = auth.IsAuthenticated(ctx)
			}
			if authenticated {
				activeCount++
				PrintStatusLine(true, p.Name(),
					lipgloss.NewStyle().Foreground(ColorSuccess).Render("session active"))
			} else {
				PrintStatusLine(true, p.Name(),
					lipgloss.NewStyle().Foreground(ColorMuted).Render("installed, no active session"))
			}
		}

		if availableCount == 0 {
			fmt.Println()
			PrintWarning(E("⚠️", "[!]") + " No providers available — install at least one CLI tool")
		} else if activeCount == 0 {
			fmt.Println()
			PrintInfo("No active sessions — run 'bwenv init' to authenticate")
		}
	}

	fmt.Println()

	// ── Section: Environment variables ───────────────────────────────────
	printStatusSection(E("🌍", "[>]") + " Environment")

	sessionVars := []struct {
		name string
		desc string
	}{
		{"BW_SESSION", "Bitwarden session"},
		{"OP_SERVICE_ACCOUNT_TOKEN", "1Password service account"},
		{"DIRENV_LOG_FORMAT", "Direnv log format"},
		{"DIRENV_WARN_TIMEOUT", "Direnv warn timeout"},
	}

	for _, sv := range sessionVars {
		val, ok := os.LookupEnv(sv.name)
		if !ok {
			PrintInfoLine(sv.name, "not set")
			continue
		}

		// For sensitive variables, show masked value.
		switch sv.name {
		case "BW_SESSION", "OP_SERVICE_ACCOUNT_TOKEN":
			masked := maskValue(val)
			PrintStatusLine(true, sv.name, fmt.Sprintf("%s set (%s)", E("🔐", "**"), masked))
		case "DIRENV_LOG_FORMAT":
			if val == "" {
				PrintStatusLine(true, sv.name, "silenced (empty)")
			} else {
				PrintStatusLine(true, sv.name, fmt.Sprintf("custom: %q", val))
			}
		default:
			PrintStatusLine(true, sv.name, val)
		}
	}

	fmt.Println()

	// ── Section: Config preferences ──────────────────────────────────────
	printStatusSection(E("⚙️", "[>]") + " Preferences")

	cfg, cfgErr := config.Load()
	if cfgErr != nil {
		PrintWarningLine("Config", fmt.Sprintf("could not load: %v", cfgErr))
	} else {
		cfgPath, _ := config.ConfigPath()
		if cfgPath != "" {
			if _, statErr := os.Stat(cfgPath); statErr == nil {
				PrintInfoLine("Config file", ShortenHomePath(cfgPath))
			} else {
				PrintInfoLine("Config file", "not created yet (using defaults)")
			}
		}

		PrintKeyValue("Emoji", OnOff(cfg.ShowEmoji))
		PrintKeyValue("Direnv Output", OnOff(cfg.ShowDirenvOutput))
		PrintKeyValue("Export Summary", OnOff(cfg.ShowExportSummary))
	}

	fmt.Println()

	// ── Quick hints ─────────────────────────────────────────────────────
	hint := lipgloss.NewStyle().
		Foreground(ColorMuted).
		Italic(true).
		Render(fmt.Sprintf("  Run '%s' to change preferences or '%s' for usage examples.",
			lipgloss.NewStyle().Bold(true).Render("bwenv config"),
			lipgloss.NewStyle().Bold(true).Render("bwenv examples")))
	fmt.Println(hint)
	fmt.Println()

	return nil
}

// ── Helpers ─────────────────────────────────────────────────────────────────

// envrcState represents the possible states of .envrc in the current directory.
type envrcState int

const (
	envrcMissing envrcState = iota // No bwenv project file found.
	envrcPresent                   // .envrc exists but was not generated by bwenv.
	envrcBwenv                     // Project metadata resolves through a bwenv backend.
	envrcInvalid                   // Project activation metadata could not be read.
)

// envrcInfo holds information parsed from the .envrc file.
type envrcInfo struct {
	state      envrcState
	provider   string   // Provider slug from the canonical project source.
	folder     string   // Folder name from the canonical project source.
	folderID   string   // Provider folder ID, when the fast lookup path is configured.
	itemIDs    []string // Optional specific items selected for this project.
	activation string
	canonical  bool
	problem    string
}

// checkEnvrcStatus prefers canonical project metadata and falls back to legacy
// generated .envrc files.
func checkEnvrcStatus() envrcInfo {
	_, projectErr := os.Stat(".bwenv.toml")
	canonical := projectErr == nil
	if projectErr != nil && !os.IsNotExist(projectErr) {
		return envrcInfo{state: envrcInvalid, canonical: true, problem: projectErr.Error()}
	}
	if !canonical {
		content, err := os.ReadFile(".envrc")
		if err != nil {
			if os.IsNotExist(err) {
				return envrcInfo{state: envrcMissing}
			}
			return envrcInfo{state: envrcInvalid, problem: err.Error()}
		}
		if !strings.Contains(string(content), "bwenv") {
			return envrcInfo{state: envrcPresent}
		}
	}

	info := envrcInfo{state: envrcBwenv, canonical: canonical}

	// Resolve metadata through the selected activation backend.
	activator, activationErr := activation.ForProject()
	if activationErr != nil {
		return envrcInfo{state: envrcInvalid, canonical: canonical, problem: activationErr.Error()}
	}
	info.activation = activator.Name()
	source, resolveErr := activator.Resolve()
	if resolveErr != nil {
		return envrcInfo{state: envrcInvalid, canonical: canonical, problem: resolveErr.Error()}
	}
	info.provider = source.ProviderSlug
	info.folder = source.FolderName
	info.folderID = source.FolderID
	info.itemIDs = source.ItemIDs

	return info
}

// printStatusSection prints a compact section header for the status output.
func printStatusSection(title string) {
	styled := lipgloss.NewStyle().
		Bold(true).
		Foreground(ColorPrimary).
		Render(title)

	divider := lipgloss.NewStyle().
		Foreground(ColorSubtle).
		Render(strings.Repeat("─", 36))

	fmt.Printf("  %s\n  %s\n", styled, divider)
}

// maskValue returns a masked version of a secret value, showing only
// the first 4 and last 4 characters with dots in between.
func maskValue(val string) string {
	if len(val) <= 12 {
		return strings.Repeat("*", len(val))
	}
	return val[:4] + "..." + val[len(val)-4:]
}

// checkDirenvHook checks if the direnv hook is configured in any shell RC file.
func checkDirenvHook() {
	if rc, ok := findDirenvHook(); ok {
		shortPath := ShortenHomePath(rc)
		PrintStatusLine(true, "direnv hook", fmt.Sprintf("found in %s", shortPath))
		return
	}

	PrintWarningLine("direnv hook", "not found in shell config — add it to your shell RC file")

	// Detect shell for a helpful hint.
	shellName := filepath.Base(os.Getenv("SHELL"))
	switch shellName {
	case "bash":
		PrintInfoLine("  Add to ~/.bashrc:", `eval "$(direnv hook bash)"`)
	case "zsh":
		PrintInfoLine("  Add to ~/.zshrc:", `eval "$(direnv hook zsh)"`)
	case "fish":
		PrintInfoLine("  Add to config.fish:", "direnv hook fish | source")
	default:
		PrintInfoLine("  See:", "https://direnv.net/docs/hook.html")
	}
}

func findDirenvHook() (string, bool) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", false
	}

	shellConfigs := []string{
		filepath.Join(home, ".bashrc"),
		filepath.Join(home, ".bash_profile"),
		filepath.Join(home, ".zshrc"),
		filepath.Join(home, ".zprofile"),
		filepath.Join(home, ".config", "fish", "config.fish"),
		filepath.Join(home, ".profile"),
	}
	if runtime.GOOS == "windows" {
		shellConfigs = append(shellConfigs,
			filepath.Join(home, "Documents", "PowerShell", "Microsoft.PowerShell_profile.ps1"),
			filepath.Join(home, "Documents", "WindowsPowerShell", "Microsoft.PowerShell_profile.ps1"),
		)
	}

	for _, rc := range shellConfigs {
		content, readErr := os.ReadFile(rc)
		if readErr != nil {
			continue
		}

		contentStr := string(content)
		if strings.Contains(contentStr, "direnv hook") ||
			strings.Contains(contentStr, "direnv export") {
			return rc, true
		}
	}
	return "", false
}
