// Package ui — status flow for showing current bwenv state at a glance.
// This file implements the "bwenv status" command which displays a compact
// overview of active sessions, .envrc presence, config state, and provider
// availability without running full diagnostics like "bwenv test".
package ui

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/lipgloss"
	"github.com/s1ks1/bwenv/internal/config"
	"github.com/s1ks1/bwenv/internal/envrc"
	"github.com/s1ks1/bwenv/internal/provider"
)

// RunStatusFlow displays a comprehensive status overview of the current bwenv state.
// This is the single diagnostic command — it combines the previous "status" and "test"
// into one clean output that covers everything:
//
//	1. Current directory & .envrc status
//	2. Core dependencies (direnv)
//	3. Provider availability and sessions
//	4. Direnv hook configuration
//	5. Relevant environment variables
//	6. Current config preferences
func RunStatusFlow(version string) error {
	PrintBanner(version)
	fmt.Println()

	// ── Section: Current directory & .envrc ──────────────────────────────
	printStatusSection(E("📂", "[>]") + " Current Directory")

	cwd, err := os.Getwd()
	if err != nil {
		PrintWarningLine("Working directory", "could not determine")
	} else {
		shortCwd := ShortenHomePath(cwd)
		PrintKeyValue("Directory", shortCwd)
	}

	// Check for .envrc in the current directory.
	envrcStatus := checkEnvrcStatus()
	switch envrcStatus.state {
	case envrcMissing:
		PrintStatusLine(false, ".envrc", "not found — run 'bwenv init' to create one")
	case envrcPresent:
		PrintStatusLine(true, ".envrc", E("📄", "->")+" found (not generated by bwenv)")
	case envrcBwenv:
		detail := fmt.Sprintf("%s bwenv-managed", E("📄", "->"))
		if envrcStatus.provider != "" {
			detail += fmt.Sprintf(" | provider: %s", envrcStatus.provider)
		}
		if envrcStatus.folder != "" {
			detail += fmt.Sprintf(" | folder: %s", envrcStatus.folder)
		}
		PrintStatusLine(true, ".envrc", detail)
	}

	fmt.Println()

	// ── Section: Core dependencies ──────────────────────────────────────
	printStatusSection(E("📦", "[>]") + " Dependencies")

	// Check direnv
	if direnvPath, lookErr := exec.LookPath("direnv"); lookErr == nil {
		PrintStatusLine(true, "direnv", direnvPath)
	} else {
		PrintStatusLine(false, "direnv", "not found — install from https://direnv.net/")
	}

	// Check direnv hook in shell config
	checkDirenvHook()

	fmt.Println()

	// ── Section: Provider sessions ───────────────────────────────────────
	printStatusSection(E("🔑", "[>]") + " Providers")

	allProviders := provider.All()
	if len(allProviders) == 0 {
		PrintWarningLine("Providers", "no providers registered (this is a bug)")
	} else {
		activeCount := 0
		availableCount := 0
		for _, p := range allProviders {
			if !p.IsAvailable() {
				PrintStatusLine(false, p.Name(),
					fmt.Sprintf("'%s' not installed", p.CLICommand()))
				continue
			}

			availableCount++

			if p.IsAuthenticated() {
				activeCount++
				PrintStatusLine(true, p.Name(),
					lipgloss.NewStyle().Foreground(ColorSuccess).Render("session active"))
			} else {
				PrintStatusLine(true, p.Name(),
					lipgloss.NewStyle().Foreground(ColorMuted).Render("installed, no active session"))
			}
		}

		if availableCount == 0 {
			fmt.Println()
			PrintWarning(E("⚠ ", "!") + " No providers available — install at least one CLI tool")
		} else if activeCount == 0 {
			fmt.Println()
			PrintInfo("No active sessions — run 'bwenv init' to authenticate")
		}
	}

	fmt.Println()

	// ── Section: Environment variables ───────────────────────────────────
	printStatusSection(E("🌍", "[>]") + " Environment")

	sessionVars := []struct {
		name string
		desc string
	}{
		{"BW_SESSION", "Bitwarden session"},
		{"OP_SERVICE_ACCOUNT_TOKEN", "1Password service account"},
		{"DIRENV_LOG_FORMAT", "Direnv log format"},
		{"DIRENV_WARN_TIMEOUT", "Direnv warn timeout"},
	}

	for _, sv := range sessionVars {
		val, ok := os.LookupEnv(sv.name)
		if !ok {
			PrintInfoLine(sv.name, "not set")
			continue
		}

		// For sensitive variables, show masked value.
		switch sv.name {
		case "BW_SESSION", "OP_SERVICE_ACCOUNT_TOKEN":
			masked := maskValue(val)
			PrintStatusLine(true, sv.name, fmt.Sprintf("%s set (%s)", E("🔐", "**"), masked))
		case "DIRENV_LOG_FORMAT":
			if val == "" {
				PrintStatusLine(true, sv.name, "silenced (empty)")
			} else {
				PrintStatusLine(true, sv.name, fmt.Sprintf("custom: %q", val))
			}
		default:
			PrintStatusLine(true, sv.name, val)
		}
	}

	fmt.Println()

	// ── Section: Config preferences ──────────────────────────────────────
	printStatusSection(E("⚙", "[>]") + "  Preferences")

	cfg, cfgErr := config.Load()
	if cfgErr != nil {
		PrintWarningLine("Config", fmt.Sprintf("could not load: %v", cfgErr))
	} else {
		cfgPath, _ := config.ConfigPath()
		if cfgPath != "" {
			if _, statErr := os.Stat(cfgPath); statErr == nil {
				PrintInfoLine("Config file", ShortenHomePath(cfgPath))
			} else {
				PrintInfoLine("Config file", "not created yet (using defaults)")
			}
		}

		PrintKeyValue("Emoji", OnOff(cfg.ShowEmoji))
		PrintKeyValue("Direnv Output", OnOff(cfg.ShowDirenvOutput))
		PrintKeyValue("Export Summary", OnOff(cfg.ShowExportSummary))
		PrintKeyValue("Auto Sync", OnOff(cfg.AutoSync))
	}

	fmt.Println()

	// ── Quick hints ─────────────────────────────────────────────────────
	hint := lipgloss.NewStyle().
		Foreground(ColorMuted).
		Italic(true).
		Render(fmt.Sprintf("  Run '%s' to change preferences or '%s' for usage examples.",
			lipgloss.NewStyle().Bold(true).Render("bwenv config"),
			lipgloss.NewStyle().Bold(true).Render("bwenv examples")))
	fmt.Println(hint)
	fmt.Println()

	return nil
}

// ── Helpers ─────────────────────────────────────────────────────────────────

// envrcState represents the possible states of .envrc in the current directory.
type envrcState int

const (
	envrcMissing envrcState = iota // No .envrc file found.
	envrcPresent                   // .envrc exists but was not generated by bwenv.
	envrcBwenv                     // .envrc exists and was generated by bwenv.
)

// envrcInfo holds information parsed from the .envrc file.
type envrcInfo struct {
	state    envrcState
	provider string // Provider slug extracted from the .envrc (if bwenv-generated).
	folder   string // Folder name extracted from the .envrc (if bwenv-generated).
}

// checkEnvrcStatus checks for .envrc in the current directory and parses
// basic metadata from it if it was generated by bwenv.
// Delegates to envrc.ParseEnvrcConfig() to avoid duplicating parsing logic.
func checkEnvrcStatus() envrcInfo {
	// Quick existence check.
	content, err := os.ReadFile(".envrc")
	if err != nil {
		return envrcInfo{state: envrcMissing}
	}

	// Check if it was generated by bwenv.
	if !strings.Contains(string(content), "bwenv") {
		return envrcInfo{state: envrcPresent}
	}

	info := envrcInfo{state: envrcBwenv}

	// Use the canonical parser from the envrc package.
	prov, folder, parseErr := envrc.ParseEnvrcConfig()
	if parseErr == nil {
		info.provider = prov
		info.folder = folder
	}

	return info
}

// printStatusSection prints a compact section header for the status output.
func printStatusSection(title string) {
	styled := lipgloss.NewStyle().
		Bold(true).
		Foreground(ColorPrimary).
		Render(title)

	divider := lipgloss.NewStyle().
		Foreground(ColorSubtle).
		Render(strings.Repeat("─", 36))

	fmt.Printf("  %s\n  %s\n", styled, divider)
}

// maskValue returns a masked version of a secret value, showing only
// the first 4 and last 4 characters with dots in between.
func maskValue(val string) string {
	if len(val) <= 12 {
		return strings.Repeat("*", len(val))
	}
	return val[:4] + "..." + val[len(val)-4:]
}

// checkDirenvHook checks if the direnv hook is configured in any shell RC file.
func checkDirenvHook() {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}

	shellConfigs := []string{
		filepath.Join(home, ".bashrc"),
		filepath.Join(home, ".bash_profile"),
		filepath.Join(home, ".zshrc"),
		filepath.Join(home, ".zprofile"),
		filepath.Join(home, ".config", "fish", "config.fish"),
		filepath.Join(home, ".profile"),
	}

	for _, rc := range shellConfigs {
		content, readErr := os.ReadFile(rc)
		if readErr != nil {
			continue
		}

		contentStr := string(content)
		if strings.Contains(contentStr, "direnv hook") ||
			strings.Contains(contentStr, "direnv export") {
			shortPath := ShortenHomePath(rc)
			PrintStatusLine(true, "direnv hook", fmt.Sprintf("found in %s", shortPath))
			return
		}
	}

	PrintWarningLine("direnv hook", "not found in shell config — add it to your shell RC file")

	// Detect shell for a helpful hint.
	shellName := filepath.Base(os.Getenv("SHELL"))
	switch shellName {
	case "bash":
		PrintInfoLine("  Add to ~/.bashrc:", `eval "$(direnv hook bash)"`)
	case "zsh":
		PrintInfoLine("  Add to ~/.zshrc:", `eval "$(direnv hook zsh)"`)
	case "fish":
		PrintInfoLine("  Add to config.fish:", "direnv hook fish | source")
	default:
		PrintInfoLine("  See:", "https://direnv.net/docs/hook.html")
	}
}
